# Timestamped Transcription of Bengali YouTube Videos

### Model Setup

In [ ]:
import ctypes

for dll in [
    r"venv\Lib\site-packages\nvidia\cublas\bin\cublas64_12.dll",
    r"venv\Lib\site-packages\nvidia\cudnn\bin\cudnn64_9.dll",
]:
    ctypes.CDLL(dll)

print("CUDA DLLs loaded")

CUDA DLLs loaded

### Transcription Helper Function

In [3]:
import jiwer
import os
import csv
import string
import re
import time
import pandas as pd
from IPython.display import display

def stream_chunks(segments, max_gap=1.0, max_words=5):
    words, start, end, previous_end = [], None, None, None
    for segment in segments:
        for word in segment.words:
            text = word.word.strip()
            should_split = words and (
                word.start - previous_end > max_gap
                or words[-1].endswith((".", "?", "!"))
                or len(words) >= max_words
            )
            if should_split:
                yield {"start": start, "end": end, "text": " ".join(words)}
                words, start = [], None
            if not words:
                start = word.start
            words.append(text)
            end = previous_end = word.end
    if words:
        yield {"start": start, "end": end, "text": " ".join(words)}

def calculate_metrics(gt_text, pred_text, title):
    gt_clean = re.sub(r'\s+', ' ', gt_text.replace('\n', ' ')).translate(str.maketrans('', '', string.punctuation + '।')).strip()
    pred_clean = re.sub(r'\s+', ' ', pred_text.replace('\n', ' ')).translate(str.maketrans('', '', string.punctuation + '।')).strip()
    
    if len(gt_clean) == 0:
        return None
        
    out = jiwer.process_words(gt_clean, pred_clean)
    cer = jiwer.cer(gt_clean, pred_clean)
    gt_words = len(gt_clean.split())
    
    return {
        "Video": title,
        "WER %": round(out.wer * 100, 2),
        "CER %": round(cer * 100, 2),
        "Word Accuracy %": round((out.hits / gt_words) * 100, 2) if gt_words > 0 else 0,
        "GT Words": gt_words,
        "Pred Words": len(pred_clean.split()),
        "Correct Words": out.hits,
        "Substitutions": out.substitutions,
        "Deletions (Missed)": out.deletions,
        "Insertions": out.insertions
    }


def run_transcription(batched_model, model_name, dataset_dir=r"dataset", output_dir=r"Outputs", **kwargs):
    os.makedirs(output_dir, exist_ok=True)
    metadata = []
    if os.path.exists(os.path.join(dataset_dir, "metadata.csv")):
        with open(os.path.join(dataset_dir, "metadata.csv"), 'r', encoding='utf-8') as f:
            for row in csv.DictReader(f):
                metadata.append(row)

    results = []
    for row in metadata:
        title = row['Title']
        safe_title = "".join([c for c in title if c.isalnum() or c in (' ', '-', '_')]).strip().replace(' ', '_')
        audio_path = os.path.join(dataset_dir, row['Audio_File'])
        subtitle_path = os.path.join(dataset_dir, row['Subtitle_File'])
        
        if not os.path.exists(audio_path) or not os.path.exists(subtitle_path):
            continue
            
        print(f"\nTranscribing {title} with {model_name}...")
        
        start_time = time.time()
        
        transcribe_args = {
            "batch_size": 16,
            "vad_filter": True,
            "word_timestamps": True
        }
        transcribe_args.update(kwargs)
        
        segments, info = batched_model.transcribe(audio_path, **transcribe_args)

        chunks = list(stream_chunks(segments))

        print("Streaming Chunked Output:")
        output_file_content = "Streaming Chunked Output:\n"
        pred_text_raw = ""
        
        for chunk in chunks:
            line = f"{chunk['start']:.2f} - {chunk['end']:.2f}: {chunk['text']}"
            print(line)
            output_file_content += line + "\n"
            pred_text_raw += chunk['text'] + " "

        time_taken = time.time() - start_time
        footer = f"\nTranscription & Chunking took {time_taken:.2f} seconds\nTotal chunks generated: {len(chunks)}\n"
        print(footer)
        output_file_content += footer
        
        out_file = os.path.join(output_dir, f"{model_name}_{safe_title}.txt")
        with open(out_file, 'w', encoding='utf-8') as f:
            f.write(output_file_content)
            
        with open(subtitle_path, 'r', encoding='utf-8') as f:
            gt_text = f.read()
            
        metrics = calculate_metrics(gt_text, pred_text_raw, title)
        if metrics:
            results.append(metrics)

    if results:
        df = pd.DataFrame(results)
        display(df)

## Loading Model & Transcribing

### Faster-whisper-large-v3

In [2]:
from faster_whisper import WhisperModel, BatchedInferencePipeline

model = WhisperModel("large-v3", device="cuda", compute_type="float16")
batched_model = BatchedInferencePipeline(model=model)

print("Loaded batched model successfully")

Loaded batched model successfully

In [5]:
run_transcription(
    batched_model=batched_model,
    model_name="Faster-whisper-large-v3",
    language='bn',
    vad_parameters={"min_silence_duration_ms": 4000, "speech_pad_ms": 6000}
)

Transcribing Rain with Faster-whisper-large-v3...
Streaming Chunked Output:
0.00 - 2.08: দোখিন্বঙ্গে আজ ও কাল ভারি
2.08 - 4.52: বৃষ্টির সম্ভাবনা কলকাতায় দফায় দফায়
4.52 - 6.78: বৃষ্টির সম্ভাবনা থাকছে শুক্রুবার থেকে
6.78 - 7.38: এই বৃষ্টি �
16.65 - 19.57: অন্ন জেলাতেও বিখিপ্ত দোযাক পাসলা
19.57 - 22.39: বৃষ্টির সম্বাবনা থাকছে শোনি এবং
22.39 - 24.91: রবিবার দোখিন বঙ্গে বৃষ্টির পরিমান
24.91 - 41.93: কোম্বে আর অন�
44.01 - 47.05: এমোটে মরসুমে অখ্যরেখা মরশিদাবাদ থেকে
47.05 - 49.33: গাঙ্গিয় দক্ষিন মঙ্গের প্রায় অপর
49.33 - 51.37: দিয়ে বাংলাদেশ পরজন্ত বিস্তিতো সেই
51.37 - 63.85: মরসু� 30 থেকে 40 কিলমিটের
63.85 - 65.39: বেগে দমকা জহরা হাওয়ার পুর্বা
65.39 - 67.21: ভা শুলো এছে উপকুলের জিলার
67.21 - 68.97: খেত্রে এই দমকা জহরা হাওয়ার
68.97 - 70.27: গতিবেক কোনকনো �
77.40 - 79.66: এই অবস্থা বৃহস্পতিবার পরজন্ত চলার
79.66 - 81.60: পর শুক্র, সনি এবং রবি,
81.68 - 83.92: উত্তর এবং দখিন বঙ্গে লক্খনিয়
83.92 - 107.38: ভাবে বৃষ্টি পাতের পরিমান কোম�
108.51 - 112.11: BANGALORE AWACH, BANGALI RABIC, ZEE
112.11 - 112.81: 26 GONTA

Transcription & Chunking took 4.89 seconds
Total chunks generated: 22


Transcribing Delhi Protest with Faster-whisper-large-v3...
Streaming Chunked Output:
22.18 - 25.94: মাতির সুকার 1000 -ও আংদলনকারি
25.94 - 28.36: নিরাপত্তা বেরিকেট ভেঙে সংশত ভাবনের
28.36 - 30.44: মুল ফটকেট দিগে অগ্রশোর হন।
30.44 - 36.76: এ সময় ভাবনের ভেতরেই প্রধান
36.76 - 47.15: মন্ত্রি উপ
48.93 - 51.63: শিখার্থিদের আন্দলনে বুলিছের বেবক লাঠি
51.63 - 53.87: চার্জ এবং রাবার বুলেট নিখেবের
53.87 - 55.45: পর এই আন্দলন এখন
65.12 - 67.44: May মাশে জাত্টা শুরু করার
67.44 - 69.96: পার্থেকে CJP সোষাল মিডিযাই লক্খ
69.96 - 72.38: লক্খ অনুশারি অর্জন করেছে যা
72.38 - 75.84: 2024ে ত্রিতিয় বারের মতো খমতায়
75.84 - 85.45: আশার প CJP -র আশুতোষ
85.45 - 87.63: একটি সোষাল মিডিযা পোষ্টে বলেছেন
87.63 - 89.99: আমরা থামো না প্রধান কে
89.99 - 93.13: বরখাস্ত করতে ই হবে মংগল
93.13 - 94.63: বারো সতো সতো বিখ্যপ কারি
94.63 - 94.69:
108.54 - 110.78: সোম্বার প্রাই পাঁচ বছোরের মধ্যে
110.78 - 112.80: দিল্লির অন্নতম বৃহক্তম এক গনো
112.80 - 115.84: সমাবেশে বিক্খপকারিদের সংশদ ভিমুখে মিছিল
115.84 - 134.68: করতে বাধা

Transcription & Chunking took 4.61 seconds
Total chunks generated: 22


Transcribing Subhendu CM with Faster-whisper-large-v3...
Streaming Chunked Output:
0.00 - 3.20: Mamata Bandopadhyay জে হেরে গিযেছেন
3.20 - 5.22: সেটাই কারজতো মেনে নিত্ছিলেন না
5.22 - 7.60: Mamata Bandopadhyay কিন্তু না অবশেশে
7.60 - 10.24: শুবেন্দু অধিকারিকে মুখ্যমন্ত্রি সেবে
19.28 - 21.48: কে মুখ্য মন্ত্রি মান্লেন মমতা
21.48 - 22.32: বন্ধ পাদ্ধায়
37.00 - 38.16: এবং আপনার জনো আমি বার
38.16 - 40.18: বার যেতাম আপনার কেন্ডে সেটা
40.18 - 41.60: আমার কর্তোব্ব ছিলো এর জনো
41.60 - 43.24: আমি কোনো কিছিতো নিছিনা
56.04 - 58.20: 4 মে ফল প্রকাশের পার
58.20 - 60.52: পমতা বন্দো পাদায় তিনি রাজ্ভাবনে
60.52 - 62.38: ও জান্নি ইস্তাফা দিতে আমন
62.38 - 63.44: কি তার পারে তিনি যে
63.44 - 75.30: শাংবাদিক শান্বেল এবং প্রায় দিদুগো
75.30 - 76.60: সমায় ধরে তিনি তার নিজের
76.60 - 79.12: ভক্তব্বের জাইগাতে অনর ছিলেন। একাদিক
79.12 - 81.02: যেরা তৃনমুল কঙ্গ্রসের নেতারা তারা
81.02 - 81.86: �
104.36 - 106.38: এরে মদ্যাচকে দেখতে পাবাগালো যে
106.38 - 108.50: সোষাল মিডিযাতে তার পেজে যে
108.50 - 110.24: লাইফ করাছেন সে লাইফের মদ্যে
110.24 - 127.34: তিনি কার জতো ভুখাবন্তি শুব
127.12 - 128.56: এবং এমন একটা সমায় দাডিয়ে
128.56 - 130.04: তাকেই কথাগুলো বলতে ওছে যখম
130.04 - 131.84: তুনমুল কঙ্গ্রেস বলতে জে সমস্টো
131.84 - 133.78: নে তারা পরিচিত ছিলে নমতা
133.78 - 134.04: বংদো
142.36 - 144.00: এবং বমতা বন্দো বাদ্দা হয়েতো
144.00 - 146.32: বুঝদে পেরেছে যে বাস্তাবের এবং
146.32 - 148.34: যে কল্পনার জে মিশেল তার
148.34 - 149.68: দুতার মধে ফারাক কোথায়
166.06 - 167.78: এটা থিক যে তুনুমুল কঙ্গ্রসের
167.78 - 170.24: জেশমস্তো নেতারা, ভিশেজাতো সাংশাদ্রা এন্সিপিআইতে
170.24 - 185.04: জোগ দিয়েছেন, জেশমস্তো বিধাযক্রা
184.17 - 186.33: প্রাজ্য বিধানসাবা অদিবেশানের মধ্য অব্ভন্তারে
186.33 - 188.37: দারিয়ে বিরদি দলনেতাকে ওই প্রশন্গুনিয়ে
188.37 - 189.37: কটাক্কো কমতে সরনায়
203.02 - 205.12: পলে সেই ঘটনার পুক্রম তার
205.12 - 206.72: রেষ কান্তেগি আজিকে যেটা পলেছেন
206.72 - 208.90: তাতেটা পরিশকার যে বক্তপ্ব তিনি
208.90 - 213.32: রেকে ছিলেন বাস্তাবের মাঠ�
221.16 - 222.72: কে এবং তার দলের ভাংগন
222.72 - 224.22: যে পডিবানে পাক্তে শুরু করেছে
224.22 - 234.82: তাতে অনেকি ইমোর্তে শুরু করেছে
236.67 - 238.65: Gini আজকে মুখ্য মন্তি হোয়েছেন
238.65 - 240.15: আমার অনেক শুবেচ্ছা ভাগে কিন্তু
240.15 - 241.27: এটা আমি নিস্ট্রেই বলো না
241.27 - 256.41: আপনি মুখ্য মন্তি হোয়েছেন ব�

Transcription & Chunking took 8.89 seconds
Total chunks generated: 49


Transcribing Dengue with Faster-whisper-large-v3...
Streaming Chunked Output:
0.00 - 2.38: ভারতে প্রথম্মার আস্ছে ডেঙ্গি ঵াক্সিন
2.38 - 4.80: ক্যু ডেঙ্গা ঵াক্সিন বানিজ্জিক ভাবে
4.80 - 7.12: বিক্রির অনুমদন দিলো ড্রাক কন্ট্রল
7.12 - 11.92: জেন�
17.74 - 20.70: প্রতিবাছোর মসামাহিতো রোগে আক্টান্তোহন হাজার
20.70 - 22.82: হাজার মান্স্ সেই দরাইয়ে এবার
22.82 - 24.66: নোতুন হাতিয়া পেলো দেশ ভারতে
24.66 - 33.69: প্রথম মা ্যাপানে তাকে তা
33.69 - 35.25: বায় ফার্মাসেয় টিকান্সে তোইডি এই
35.25 - 37.11: ভাক্সিন চাট থেকে শাট বছার
37.11 - 38.91: বশিদের দেযা হবে। সহস্থা তাবি,
38.95 - 52.22: এই ভাক্স 2 বার দেঙ্গু
52.22 - 54.92: হয়ে গেলে মানুষ দেঙ্গু ইমিউন
54.92 - 56.66: হয়ে যায় তো সেটা যদি
56.66 - 60.36: আমি আর্টিফিশালি একটা ইন্ফক্ষনের মতন
60.36 - 69.44: করে দিতে পারি ত ে
69.44 - 72.02: এই ডেংগু ফাক্সিন্টা ইস কোয়েট
72.02 - 75.12: সেফ এন এফেক্টি঵। প্রসুতাই সহস্থান
75.12 - 77.52: দাবী ডেংগু ফাইরাসের চাটি সেরোটাইপের
77.52 - 84.18: বিরুথেই শু ্যে প্রেশন্টা আকে
84.18 - 87.00: দেয়ে ইন্ফেক্টের ছিলো কি ছিলো
87.00 - 89.00: না আন্টিপোডি আছে কি নে
89.00 - 100.07: স্ট্রেয়েট ঵্যাক্সিন্টা দিয়ে দেয়ে একটা
100.07 - 101.87: ব্যাক্সিন দিলে যদি এখানে আমাদের
101.87 - 105.33: দুটো ব্যাক্সিন দিতো হবে প্রতম
105.33 - 107.49: ব্যাক্সিন তিন হস্পরে আবার সেকেন
107.49 - 117.49: ব্যাক্সিন কি 8 -8 -8
117.49 - 119.11: -8 -8 -8 -8 -8
119.11 - 119.39: -8 -8 -8 -8 -8
119.39 - 120.05: -8 -8 -8 -8 -8
120.05 - 120.05: -8 -8 -8 -8 -8
120.05 - 120.31: -8 -8 -8 -8 -8
120.31 - 120.65: -8 -8 -8 -8 -8
120.65 - 134.11: -8 -8 -8
141.97 - 145.07: 4 মাছো 3 সেপ্রিল পোর্জন্তো
145.07 - 147.59: এরাজে দেঙ্গি আখ্রান্ত হোয়েছেন 770
147.59 - 149.83: জন। বর্ষের মর্ষুমে দেঙ্গি ও
149.83 - 151.75: অন্নান্ন ভেক্টের মাহিতো রোগের সক্রমন
151.75 - 154.13: রুক্তে তথ্পার প্রশাশন। মংঙ্গল্ভার সাস্থ
154.13 - 166.19: সথিপ সা�

Transcription & Chunking took 6.83 seconds
Total chunks generated: 40


Transcribing Terrorist(Long) with Faster-whisper-large-v3...
Streaming Chunked Output:
15.36 - 17.92: নাসকার দেখছেন জিচোবিশ ঘন্টা আর
17.92 - 19.66: স্পেশল চোবিশ নিযা প্রদেশাম গেরোয়েছি
19.66 - 24.64: আমি শোইকাদ জন্গি ই নামটা
24.64 - 29.76: শুন্লেই প্রথম পাকিস
31.92 - 34.26: জন্গি বা জন্গি দেশ বলতে
34.26 - 37.06: আর কেউ নি পাকিস্তান হচ্ছে
37.06 - 39.72: জন্গিদের আতুর ঘর আমরা জানি
39.72 - 40.96: যেই ভারত কে বার বার
40.96 - 47.69: রক্তাক্ত করে ছে পা� কাস্মের
47.69 - 49.99: সঙ্লগ্ন যে রাজ্যগুলি রয়েছে বিশেশ
49.99 - 52.17: করে উত্তর ভারত এবং কিছুটা
52.17 - 54.41: উত্তর পুর্ভ ভারত কে অশান্ত
54.41 - 65.07: করা চেষ্ঠা করে রক� BANGLA
65.07 - 67.03: তে ঘাটি গেরে বসে থাক্ছে
67.03 - 70.37: সুধু তাই নায় এ রাজ্যের
70.37 - 73.01: মুখ্যমন্ত্রে শুবেন্দু অধিকারি কেও হত্তার
73.01 - 75.35: পরিকল্পনা করছে ভাপছে
80.97 - 83.27: Bengal STF -e -r নজারে
83.27 - 86.57: এই মহুত্তে হামিম মন্ডল বাংগলায়
86.57 - 88.91: ঘাটি গেরে থাকা এই জন্গির
88.91 - 92.29: আকাধিক তথ্য আখন গোয়ন্ডাদের হাতে
92.29 - 96.02: পুলিসের হাতে ক
102.83 - 104.87: পাকিস্তান পোর্জন্তো
113.07 - 115.63: Renesas Township, সেই Renesas Township
115.63 - 118.37: এর থিক মেপ্টা জুদি বজনত
118.37 - 119.83: চেস্টা করি, কেনো মেপ্টা বজনত
119.83 - 121.69: চেস্টা করছি, কারন এই Renesas
121.69 - 123.09: Township এই কেনো সে ঘাটি
123.09 - 132.36: গেরে ছিলো, কা পাসেই দুতো
132.36 - 135.66: স্কুল রয়েছে জাতে বরো নাশকতা
135.66 - 137.00: ঘটালে এই স্কুল কে বেছেনে
137.00 - 139.16: মাজেতে পারে সপিংগ মাল অর্থাদ
139.16 - 140.86: বরো নাশকতা বেশি মা�
154.86 - 158.00: সপ্ছে বারো কথা বার্ধোমানের খাগ্রাগর
158.00 - 160.66: জে খাগ্রাগর বিশ্পরনের পার এনায়
160.66 - 162.60: তদন্তে উঠে সেছিলো জন্গি মডিউল
162.60 - 173.45: জেশ জন্গি মডি তার পেছনে
173.45 - 176.59: কি বরো কনো নাশকতার পরিকল্পনা
176.59 - 179.21: ছিলো আর এই জন্য মানুষের
179.21 - 181.67: সংগে মিশে থাক্ত এই জন্যিরা
190.28 - 192.16: মানে করুন আপনি জিমে শরি
192.16 - 194.44: চর্চা করছেন কিংবাপ সব্জির বাজারে
194.44 - 197.44: সব্জির দর্দাম করছেন ঘুনাক খরো
197.44 - 199.02: টেন পারছেন না আপনার পাসে
199.02 - 199.28: দার�
204.76 - 206.78: তেমনি বোঝার উপায় ছিলো না
206.78 - 209.58: সে আয়সাই নিজুক্ত ন্রিসংশ জঙ্গি
209.58 - 212.76: সংগথন জেশের সদশো পরিছায় লুকতে
212.76 - 214.30: কখনো সে দর্জির কাজ করতো
214.30 - 226.30: ব�
229.19 - 231.89: Barthoman সহর থেকে হারার পিলঘানা.
235.37 - 238.25: বাংগলায় খমতা এশেই অনুপ্রভেশকারি আটকাতে
238.25 - 240.71: শিমান্তে বেরাদিতে জুমি দিয়েছেন বিয়েসেফকে.
256.19 - 257.13: শু�
259.25 - 261.67: কোনো ঘিন্জি সহর বা এলাকায়
261.67 - 264.55: কোনো অপারেশনের আগে জন্গিরা সাধারনতো
264.55 - 266.51: মানুষের মধ্যে মিশে থাকে এটা
266.51 - 274.11: জন্গিদের চিরা চরিত পা�
277.79 - 280.05: হারার পিলখানা অত্তন্ত জনোবহুল একটি
280.05 - 282.07: এলাকা এই অন্ছলে বেশি সংখালো
282.07 - 284.37: গুদেরি বসোবাশ সেখানে একটি গেন্জি
284.37 - 306.80: কারখানা কাজ করতো জ
318.08 - 319.84: পাকিস্তানি এজেন্সের কথা বলে মোটা
319.84 - 324.45: টাকা দাবি করা হয়ে BJP
324.45 - 325.91: অফিসের ছোবি পাঠিয়ে হামলা রুম
325.91 - 339.91: কিয় দেবা হয়।
347.60 - 358.35: আমার মনেছে তারিপ পরিনামেটায় পাদস্ত
358.35 - 360.93: আদিকালিকের জালান এবং তারপার সেই
360.93 - 363.27: তাদন্তো কিন্তু এস্টিয়াপ করছিলো এবং
363.27 - 365.33: এই তাদন্তের প্রক্ষিতেই জে হামিদ
365.33 - 381.35: কে গে�
385.27 - 387.81: আরেক্তু তথ্য দালাশ আরেক্তু বিস্লেশনের
387.81 - 389.29: জন্ন আমাদে দুই প্রতিমিথি আমাদের
389.29 - 403.77: সঙ্গে ইমুর্তে রোয়েছেন দেবপ্রতো রোয়ে
403.72 - 405.22: একটু দেবপ্রতোর কাছে চলে যাবো
405.22 - 407.32: দেবপ্রতো হাওরার পিল্খানা একটা অত্তন্ত
407.32 - 410.48: ঘিন্জি এলাকা সেই ঘিন্জি এলাকাতেই
410.48 - 411.60: কি আত্ত গোপ�
419.02 - 420.94: a মন্টাই মুলে করা হচে
420.94 - 422.76: তার কারণ হাওড়ার পিল্খানা একে
422.76 - 424.80: পারে উত্তন্ত গিন্জি এলাকা একানে
424.80 - 426.94: সংখালগু সংপ্রদায় মালোজন মুলতো �
437.87 - 439.81: a জোর্জির কাছ্পোর তো এবং
439.81 - 441.37: এখানে ঘোর ভারা নিয়ে থাক্তো
441.37 - 442.73: এই হামেন আমন্তে যামে জান্তে
442.73 - 444.73: পাচে পুলিশুত্রে এবং এখান তেকে
444.73 - 456.84: ব operation চালি হিরে বা
456.84 - 458.08: কিকি হরো দে ছাক কাসাও
458.08 - 459.64: চিরে সমস্ত্রাই তাকে জিগ্যা সমাত
459.64 - 461.22: করে দাখাও ছে তু ওত্তন্ত
461.22 - 474.58: চান্চান লোকর অবিয়গ যেট এবং
474.58 - 478.50: তারমানে এই ভুল্টাই কারজত পুলিস
478.50 - 480.60: কে পউছে দিলো এই হামিম
480.60 - 482.58: পরজন্তো আমি একটু চলে জাবো
482.58 - 488.88: আমাদের প্রতিনিথি ওযন সন্বার রেছে
488.76 - 491.36: সেখানেই কারজোতো ঘাটি গেরেছে এবং
491.36 - 493.04: তার লোকেশন গুলো জদি আমরা
493.04 - 494.72: দেখি খাগ্রাগর কাছে জাতিয় সরক
494.72 - 497.24: কাছে স্কুল কাছে কিআনো বর্�
508.50 - 510.32: কানে তুমাকে বলে রাখে তুমি
510.32 - 512.10: জানা যো ন্যুটাউনো সাপোর জিতে
512.10 - 514.34: যে আবাসন্ডোছে সিটাও কিন্তু বিশাল
514.34 - 526.42: একটা জাইগা জুরে একটা সেখা�
526.41 - 528.45: 90 একার জাইগা জুরে রেনেসার
528.45 - 530.05: টাউন জিম। মান তারমাদে তমাখে
530.05 - 531.93: বলোরে কি যে বহু বিলাজ
531.93 - 533.87: বুল আবাছন রচে। আমি একার
533.87 - 539.97: যে জিমে আস্তেন তি� আমার
539.97 - 541.61: হাতে যেটা রোছে গাইডলাইন রোছে
541.61 - 543.39: দাখো সেই গাইডলাইন একিতু একারো
543.39 - 556.51: বেরিফিকিশেনে যে প্রসেশে বেরিফিকিশেনে প্রসেশ
556.51 - 556.65: প�
557.77 - 560.11: HM পাসাবারশি একটা রেজিস্টার দাখায়
560.11 - 562.13: যে রেজিস্টার এটা প্রিশে রেজিস্টার
562.13 - 563.99: যে জিমে আস্তো এক মাসার
563.99 - 570.53: জন্য জিমে এস্ছিলো হাম� ্যার
570.53 - 575.21: ক্ষেয়ের ক্ষেয়ের ক্ষেয়ের ক্ষেয়ের ক্ষেয়ের
575.21 - 589.78: ক্ষেয়ের ্যে সেকে নে কিন্তু
589.78 - 592.16: প্লিস বেরিফিকসন করিয়ে তাকে কিন্তু
592.16 - 594.02: রেন্টে দিয়া। সেকে তাই যখন
594.02 - 607.32: ওনি এখনে এড্মিসন করতে এস্ট
607.32 - 607.96: চিল�
621.66 - 623.60: না তাকে কে উনি দেখেছিলেন
623.60 - 625.10: দেখে জঙ্গি জঙ্গি ভাব মনে
625.10 - 625.50: হয়ে হয়ে ছিলো
629.15 - 630.99: দেখে দেখে মনে হচ্ছলো তার
630.99 - 633.99: জে আচার বেভোহার দেখে মনে
633.99 - 637.97: হচ্ছলো তার জে আচার বেভোহার
637.97 - 639.93: দেখে মনে আপনি ভাক্তা বারবের
639.93 - 648.09: না কি �
667.97 - 671.11: exactly এতাইত পোয়ন্ট আযন তুমি
671.11 - 673.05: সঙ্গে থাকো আমাদেশ সঙ্গে রেয়াছেন
673.05 - 675.31: কনেল দিপতাংশো চোধুরি কনেল চোধুরি
675.31 - 677.60: এইটা HOND করছে আমি একারণ
677.60 - 679.58: এই প্রস্টাটা করলাম সাধানন্ত যারা
679.58 - 680.94: জঙ্গি হয় তারা কম কথা
680.94 - 682.22: বলে কম মেলা মেশা করে
682.22 - 693.66: তাদের বাইরের জগদের সংগে আমি
693.66 - 695.58: প্রথমে দুতিম কথা বলি জালা
695.58 - 699.20: দর্শক্রা দেখছেন সবাই মনে করবেন
699.20 - 701.46: যে এজেন্সিরা কেনো ধুত্তে পারে
701.46 - 711.42: কিরম করে ধুত্তে পারে
711.23 - 714.13: একটা পিলখানা হাওরায়ে ঘুরে বালাছে
714.13 - 717.67: সেখানে ও এক্ছলি তোরিকোতো গেন্জি
717.67 - 720.97: দোকানে বার কো তারপোর সেখান
720.97 - 727.21: দিকে রাজার হাট পার ছ
727.23 - 730.73: RENESA, একদো মেন রোডের, বার্দমানের
730.73 - 732.75: মেন হাইবের থিক বাদিকে RENESA
732.75 - 735.03: HOUSING COMPLEX সেখানে প্রস্ত লোগ
735.03 - 736.87: থাকে সেখানে মুপেন্ট করছে জিমে
736.87 - 741.41: ধরেছ�
743.51 - 745.89: Agencies এক্স্টেরনাল অতবার ইক্স্টেরনাল, IB,
746.17 - 748.81: Research and Analysis Wing তারা
748.81 - 751.15: কিন্তু মনিটার করছে এর মুভ্মেন্ট,
751.17 - 753.57: যারা এদেশ সংগে যুক্ত, যারা
753.57 - 759.69: তার হ্যান্লা কারন তাকে বার্তে
759.69 - 762.75: দেয়া হয়ে তার মডেল কি
762.75 - 764.97: তার টেম্পলেট কি কে কেও
764.97 - 766.63: সংগে যোগা যোগ রাস্ছে কে
766.63 - 776.49: যোগা যোগ রাস্ছে কে যোগা
776.49 - 778.26: য A আরাকটা আমি আপনার
778.26 - 780.62: জিন মধ্যে দিয়ে বলতে চাই
780.62 - 783.36: যে যামন আমনা তেরেকি তালিবান
783.36 - 787.14: পাকিস্থান শুনেছে একটা মধ্যে সংগতন
787.14 - 806.80: ভারত বার্ষ তো ওটা বিবিন্নোয়ে
806.80 - 813.28: ছোটা ছোটা সংগ্যতো প্রসংগে আমিতো
813.28 - 814.90: শোনা ইজে ইজে জিমের ট্রেনার
814.90 - 816.48: জিনি নাকে ট্রেন করতেন ওই
816.48 - 832.68: এক দিন দ�
833.98 - 835.08: আতোর কোতো আমি দেখে বুষ্তে
835.08 - 836.56: বাতনে ছুপ্ছা বাস্তো বেমকোতো ছুলে
836.56 - 838.36: এথো ছুপ্ছা বাস্তো কারো সাথে
838.36 - 839.70: কোনো কথা বলতো না করে
839.70 - 840.54: ছ�
861.44 - 864.24: Sajjad Bhat
872.84 - 875.48: এবং শাহাজাদ ভাট্টি এই দুই
875.48 - 878.40: নেট্যার্কের সংগে কানেক্ষান লোরেন্স বিষ্ণই
878.40 - 880.88: গাঙের সংগে কানেক্ষান জাইশি মাম্মাদে
880.88 - 885.10: সংগে ক�
890.92 - 892.82: Hamim কি এই ধরনের কোনো
892.82 - 895.68: খুন বা ছোটো কোনো এক্স্প্লোশন
895.68 - 897.00: করের পরিকল্পনা করছিলো?
908.51 - 910.63: হনো বসতি সেই সব জায়গায়
910.63 - 912.67: থাকে সেখান দিকে ওরা রিক্রুটিংগ
912.67 - 916.01: করে এবং তারা ত্রু সোষাল
916.01 - 918.55: মিডিযা অনেক গুলো ক্লোস নেট
918.55 - 925.59: সোষাল মি দরন সামিন মন্নল
925.59 - 927.51: যাকে আলাউ করবে তার থিকে
927.51 - 929.27: সবাই কেনো আসবে তার থিকে
929.27 - 931.47: কিছো আর্থিক বিনোয় ভাবে আর্থিক
931.47 - 940.11: ভাবে সাজ্য করবে তাদ�
942.14 - 944.62: সাহাজ্য করে তারা আক্রিষ্ট হবে
944.62 - 946.66: তারা সামনে আস্বে এই করে
946.66 - 949.22: তাদেন নেট্যোক্টা বারায় এবং এর
949.22 - 951.68: সাথে সাথে যে তার হানলার
951.68 - 955.86: সামি�
957.78 - 959.76: এখানে অব্যেক্টি ছিলে একটা হাই
959.76 - 961.96: ব্যাল্য টার্গে কে ছিলো মুখ্য
961.96 - 964.26: মন্দ্রি শুবেন্দু অদিকারি হত্তা করা
964.26 - 974.38: জন্নে একটা প্লেন মুখ্যমন্ত্রি মহসার
974.38 - 977.24: বানীর কাছে তার মুখ্যমন্ত্রি দেখছিলো
977.24 - 980.10: দিবিন্ন তার যে ছটা মোবাইল
980.10 - 983.82: পাওগেছে যা ইলেক্ট্রনিক এপিডেন�
990.24 - 992.02: কাজন তার সিক্যুরিটি ডিটেলে লোক
992.02 - 994.38: তাকে কি ভামে থাকে তার
994.38 - 996.86: ছবি লাপটপ থিকে কাকে পাঠার
996.86 - 998.98: ছে এবং তার যে তাকা
998.98 - 1008.10: পার্তোর আস্ছে পোয মোবাইলে অনেক
1008.10 - 1009.08: ভাবে আমি ডিলিট করে হতে
1009.08 - 1010.66: বেছেছে কোনো টাহা ভাজবেন না
1010.66 - 1013.40: এভেরিতিংগ একবার যদি এলেক্ট্রনিক এবিডেন্স
1013.40 - 1013.98: সলে আসে
1021.90 - 1023.94: পরতাত সাপ মিলে যেটা পরিষ্কার
1023.94 - 1025.90: বজাজাছে যা আপাতত যা তথ্য
1025.90 - 1028.50: সামনে আস্ছে তাতে হামিম মন্ডলে
1028.50 - 1030.32: নেটওয়ারকে শুত্র ধরে আরো বরো
1030.32 - 1030.82: �
1048.22 - 1050.54: আমরা জান্তাম যে এই জাতি
1050.54 - 1052.76: একটা প্রচেষ্টা যে হবে এটা
1052.76 - 1054.50: সাবাবিক ভাবে জান্তাম কি দামি
1054.50 - 1056.32: সংগে সংগে গোয়ন্দা জাপ্তোর এবং
1056.32 - 1069.61: প্রি একানে কোনো মিশানের জন্য
1069.61 - 1071.47: এলে একাইকাত আসে নি অতে
1071.47 - 1073.81: মিশানের সাথে অন্নরাও জোরিতো আছে
1073.81 - 1083.60: এক সাথে কোনো রাজনোইটিক বেক্তিত্�
1085.29 - 1089.27: প্রতোন্তো দুর্বাগ্গো জনো আমাদের রাজ্যের
1089.27 - 1093.37: এস্টিয়েপ ধরেশেরা খুব নেরাবত্তা সুনিশ্চিত
1093.37 - 1094.85: কারা হো আমরা আসাকোরি
1104.08 - 1106.16: সে জন্য ইধানের হয়েতো আমরা
1106.16 - 1108.80: আশা করছি নিশ্চিদ হাবে তান্ত
1108.80 - 1114.94: হাবে তান্তের সটেক বিচার নিশ্চি
1114.94 - 1115.28: হাবে
1119.10 - 1121.82: দেখুন এটা হবার ছিলো তারো
1121.82 - 1123.62: আমরায় এখমাত্র আজনোইতিক দাল আমরা
1123.62 - 1125.36: আশির দাশতেকে বলে এসেছে যে
1125.36 - 1127.02: একটা ভিনা জুত্তে ভারুণ তকলে
1127.02 - 1139.75: চকর Bিবিন্ন যায়াগায় শিশু মনে
1139.75 - 1142.59: বিদ্দেশের পিষ, দেশ্বিরো দেতার পিষ,
1143.15 - 1144.93: হিন্দু বিদ্দেশের পিষ তুক্যে দেয়া
1144.93 - 1160.00: হয়ছিন। যে পরিবে� কুবন্ত্রি নিস্চিক
1160.00 - 1162.82: ভাবে তাকে হত্তার টারগেট করে
1162.82 - 1166.36: এলে সেটা উদ্বেগের নিন্দার পাসামাশি
1166.36 - 1168.92: এই ধরনে জঙ্গি সংগঠন কুলো
1168.92 - 1173.06: সাধারা যেকানে সেকানে বমাবিস্পরণ আমনাতো
1173.06 - 1175.32: দেখেছি ভারত্বারসের বিভিন্ন জায়গায় সেনাজ
1175.32 - 1177.08: অন্দের মেরে দিয়াল পুলো আমায়
1177.08 - 1179.54: ফলে নি�
1197.19 - 1198.59: ্রেরেরেরে

Transcription & Chunking took 49.18 seconds
Total chunks generated: 248


Transcribing Taslima Nasrin(Long) with Faster-whisper-large-v3...
Streaming Chunked Output:
0.00 - 1.74: আছে কি জামতে ছেয়েছিলেন?
2.22 - 4.98: যায় গস্যামি যায় গস্যামি কে
4.98 - 6.66: ডাকুলেন তুনি শীডি পর্চতা চলে
6.66 - 23.46: গেছিলেন দার্পার দর্শক্তের একা�
29.28 - 31.98: তোআ আমি আমার জে ভাসন
31.98 - 34.82: ছিলো সিখনে তো আমি বাক্ষাদি
34.82 - 37.92: নতের কথাই গুলেছিনে ছে আমদে
37.92 - 40.18: ভিন্নমত থাক্তে পারে কিন্তু কাউ
40.18 - 49.16: সবাইকে ক আমিতো ঠিক যে
49.16 - 52.78: কথাটাই বলেছিলাম, জারা আমার কথা
52.78 - 56.16: পছন্দো করেছিলেন, তাদের মধ্যিকি তারা
56.16 - 59.70: ছিলেন জারা জাইগোর সোমিকে মন্ছি
65.15 - 68.39: একদিকে একজনের একজন যখন মধপ্রকাশের
68.39 - 71.77: অধিকারের পক্ষে বলছে তখন তম্রাতাকে
71.77 - 77.21: সমার্থন করছো কিন্তু মধপ্রকাশের অধিকারের
77.21 - 86.39: জন্ আর একজন কবিকে ডাক্ছেন
86.39 - 88.01: তুমি তখন তার কথা সম্দের
88.01 - 91.19: চাইছন তাহলে তো আমার তো
91.19 - 94.57: খারাব লাগবে আমার লেগেছে এবং
94.57 - 97.45: আশা করি এই রকম আবস্থার
97.45 - 99.11: হবে না কারণ করণ করণ
99.11 - 100.33: করণ করণ করণ করণ করণ
100.33 - 113.14: করণ করণ করণ করণ করণ
113.13 - 116.35: বিন্ন হোতে পারে কিন্তু সবারি
116.35 - 119.11: তার ভিন্ন মার প্রকাশ করের
119.11 - 121.45: অধিকার থাক্তে আমে
137.88 - 140.18: আছকে না কথা হয়েনি কিন্ত
140.18 - 144.06: আমি কথা বল্বো কথা বল্বো
144.06 - 151.58: এটা সুধু আমি আছে বা
151.58 - 153.88: কাল আমি জাবো তার বারে
153.88 - 154.82: তে কথা বল্দে
158.82 - 179.61: 3 সরকার আমাকে বেরকোলে দেয়েছিলেন
179.61 - 182.55: দিত্য সরকার আমাকে আস্তে দেননি
182.55 - 185.35: তৃত্য সরকার আমাকে
188.54 - 192.48: 3 পার্তকোটা আছে এখন সেই
192.48 - 196.96: পার্তকোটা না দেখে এই জে
196.96 - 199.16: আমি আস্তে পারেলাম সেটাকে আমার
199.16 - 201.62: মনার সেলেপ্রেট করে আছে এবং
201.62 - 202.48: আমি খুবি
204.29 - 206.55: য়া আমি আস্তে পেরেছে এবং
206.55 - 209.15: সুধু আমি বিশ্যাস করতে চাই
209.15 - 211.49: যে এই সর্কার মক্প্রকাশের অধিকারে
211.49 - 214.07: বিশ্যাস করেন এই সর্কার বাক্ষা
221.61 - 225.47: প্রকাশ করলেও আমি এখানে এই
225.47 - 229.53: সরের বাইরাজ্যে প্রভেশ করা সাধিনতা
229.53 - 233.65: পেছি সেটাক্তে আমি সিমাগত থাক্তে
233.65 - 235.69: চাই না আমি চাই অন্য
235.69 - 240.84: জা� ্যারমারে আকিরকন সাধিনতো পোপোপ
240.84 - 269.17: করে। তাহলে পিছিয়ে আছি যোতে
269.17 - 270.71: নালে আমি এগে যার চেষ্টা
270.71 - 283.67: করেবা পামাদের দিক্তে কেকে একটা
283.67 - 296.45: অপ্রভতি কোয়ে বামাদের দিক্তে একটা
296.45 - 300.34: অপ্রভতি কোয়ে পাকিস্তানে এই উপমহাদেশে
300.34 - 303.26: এই অভিন্ন দেযানিবিধির খুর দরকার
303.26 - 305.82: আসলে প্রিথিবের চেকুন সব্ভ দেশে
305.82 - 308.84: এই অভিন্ন দেযানিবিধি আছে �

,Video,WER %,CER %,Word Accuracy %,GT Words,Pred Words,Correct Words,Substitutions,Deletions (Missed),Insertions
0,Rain,81.40,65.57,20.47,215,101,44,53,118,4
1,Delhi Protest,83.87,62.55,17.74,186,98,33,62,91,3
2,Subhendu CM,87.22,71.46,13.10,626,227,82,143,401,2
3,Dengue,86.54,65.26,13.74,364,191,50,140,174,1
4,Terrorist(Long),83.46,64.16,17.49,2527,1153,442,687,1398,24
5,Taslima Nasrin(Long),78.28,56.14,22.43,2670,1472,599,854,1217,19
6,Shamik(Long),83.31,63.13,17.56,2625,1200,461,716,1448,23
7,10am News(Long),86.77,66.44,14.21,2456,1025,349,652,1455,24

### Faster-whisper-large-v3-bn-ct2

In [2]:
from faster_whisper import WhisperModel, BatchedInferencePipeline

model = WhisperModel("models\\whisper-large-v3-bn-ct2", device="cuda", compute_type="float16")

batched_model = BatchedInferencePipeline(model=model)

print("Loaded batched model successfully")

Loaded batched model successfully

In [4]:
run_transcription(
    batched_model=batched_model,
    model_name="Faster-whisper-large-v3-bn",
    language='bn',
    vad_parameters={"min_silence_duration_ms": 4000, "speech_pad_ms": 6000}
)

Transcribing Rain with Faster-whisper-large-v3-bn...
Streaming Chunked Output:
0.00 - 2.14: দক্ষিণবঙ্গে, আজ ও কাল ভারী
2.14 - 4.52: বৃষ্টির সম্ভাবনা কলকাতায় দফায় দফায়
4.52 - 6.96: বৃষ্টির সম্ভাবনা থাকছে।শুক্রবার থেকে এই
6.96 - 18.83: বৃষ্টি ক অন্য জেলাতেও বিক্ষিপ্ত
18.83 - 22.01: দুয়াগপশলা বৃষ্টির সম্ভাবনা থাকছে, সোনি
22.01 - 24.91: এবং রবিবার দক্ষিণবঙ্গে বৃষ্টির পরিমান
24.91 - 27.99: কমবে, আর অন�
43.71 - 46.71: এই মতে মৌসুমী অক্ষরেখা মরশিদাবাদ
46.71 - 49.39: থেকে গাঙ্গীয় দক্ষিণবঙ্গের প্রায় উপর
49.39 - 53.39: দিয়ে বাংলাদেশ পর্যন্ত বিস্তৃত সেই
53.39 - 63.85: মৌসুম তিরিস থেকে চল্লিশ কিলোমিটার
63.85 - 65.53: বেগে দমকা ঝোড়া হওয়ার পূর্বাভাস
65.53 - 68.39: রয়েছে।উপকূলের জেলার ক্ষেত্রে এই দমকা
68.39 - 78.76: ঝোড়া হওয়া এই অবস্থা বৃহস্পতিবার
78.76 - 81.04: পর্যন্ত চলার পর শুক্র, সনি
81.04 - 83.30: এবং রবি উত্তর এবং দক্ষিণবঙ্গে
83.30 - 107.38: লক্ষণীয়ভাবে বৃষ্টিপাতের পরিমান কম
108.43 - 112.09: বাংলার আওয়াজ বাঙালির আবেগ সি
112.09 - 112.89: চব্বিশ ঘটা

Transcription & Chunking took 5.16 seconds
Total chunks generated: 19


Transcribing Delhi Protest with Faster-whisper-large-v3-bn...
Streaming Chunked Output:
6.38 - 9.02: ছাত্রদের আন্দোলনে উত্তোপ্ত হয়ে উঠেছে
9.02 - 12.44: ভারতের রাজধানী নয়াদিল্লি। নয়াদিল্লিতে মেডিকেল
12.44 - 13.16: ভর্তি পরীক্ষা
24.72 - 27.36: হাজারও আন্দোলনকারী নিরাপত্তা বেরিকেট ভেঙ্গে
27.36 - 29.28: সংসদ ভবনের মূল ফটকের দিকে
29.28 - 36.34: অগ্রসর হন। এসময় ভবনের ভেতরেই
36.34 - 37.46: প্রধানমন্ত�
48.87 - 51.59: শিক্ষার্থীদের আন্দোলনে বুলিশের ব্যাপক লাঠি
51.59 - 53.85: -চার্চ এবং রাবার বুলেট নিক্ষেপের
53.85 - 55.61: পর এই আন্দোলন এখন।
65.28 - 67.46: মে মাসে যাত্রা শুরু করার
67.46 - 69.64: পর থেকে সিজেপি সোশাল মিডিয়ায়
69.64 - 71.90: লক্ষ লক্ষ অনুসারী অর্জন করেছে,
71.92 - 77.76: যা দুইহাজার চব্বিশ সালে তৃত�
83.63 - 86.77: সিজেপির আশুতোষ একটি সোশাল মিডিয়া
86.77 - 90.01: পোস্টে বলেছেন, ‘আমরা থামবনা’, ‘প্রধানকে
90.01 - 93.99: বর্খাস্ত করতেই হবে।মঙ্গলবারণ শত শত
93.99 - 106.69: বিক্�
108.54 - 110.80: সোম্বার প্রায় পাঁচ বছরের মধ্যে
110.80 - 113.36: দিল্লির অন্যতম বৃহত্তম এক গণসমাবেশে
113.36 - 116.14: বিক্ষোভকারীদের সংসদ অভিমুখে মিছিল করতে
116.14 - 116.48: বাধা

Transcription & Chunking took 5.04 seconds
Total chunks generated: 22


Transcribing Subhendu CM with Faster-whisper-large-v3-bn...
Streaming Chunked Output:
0.78 - 3.22: মমতা বন্দ্যোপাধ্যায় যে হেরে গিয়েছেন
3.22 - 5.24: সেটাই কার্যতঃ মেনে নিচ্ছিলেন না
5.24 - 7.68: মমতা বন্দ্যোপাধ্যায়, কিন্তু না, অবশেষে
24.50 - 27.12: তিনি আজকে মুখ্যমন্ত্রী হয়েছেন আমার
27.12 - 28.58: অনেক সুবেচ্ছা থাকবে, কিন্তু এটা
28.58 - 31.94: আমি নিশ্চুই বলমা যা আপনি
31.94 - 37.98: মুখ্যমন্ত্রী হয়েছে আবির রয়েছে আমার
37.98 - 48.68: সঙ্গে, আবিরের কাছ থেকে জানতে
48.68 - 51.90: চাইব, আবির অবশেষে সুভেন্দুকে মানলেন
51.90 - 52.60: মমতা।
56.32 - 59.06: চৌঠামে ফল প্রকাশের পর প্রমতা
59.06 - 61.44: বন্দ্যবাদ্যায় তিনি রাজভাবনেও যাননি ইস্তফা
61.44 - 63.36: দিতে, এমনকি তার পরে তিনি
63.36 - 74.96: যে সাংবাদিক সম্বে এবং প্রায়ই
74.96 - 76.26: দ্বিদুগর সময়ে ধরে, তিনি তার
76.26 - 79.14: নিজের বক্তব্যের জায়গাতে অনড় ছিলেন।একাধিক
79.14 - 95.12: যারা ত্রিণমূল কংগ্রসের নেতার�
104.36 - 106.16: এরই মধ্যাচকা দেখতে পারা গেল
106.16 - 107.96: যে সোশাল মিডিয়াতে তিনি তার
107.96 - 109.50: পেজে যে লাইভ করেছেন সেই
109.50 - 124.02: লাইভের মধ্যে তিনি কার্যতঃ মুখ্যম�
127.12 - 128.56: এবং এমন একটা সময়ে দাঁড়িয়ে
128.56 - 129.80: তাকে এই কথাগুলো বলতে হচ্ছে,
129.82 - 131.50: যখন তুনুবুল কংগ্রেস বলতে যে
131.50 - 133.62: সমষ্ট নেতারা পরিচিত ছিলেন মূব�
142.36 - 144.38: এবং ভবতা বন্দ্যবাদ্যা হয়ত বুঝতে
144.38 - 147.60: পেরেছেন যে বাস্তবের এবং কল্পনার
147.60 - 148.94: যে মিশেল তার ভূত্রের মধ্যে
148.94 - 149.96: ফারাক কোথায় রয়েছ�
166.06 - 167.78: এটা ঠিক যে ত্রিনমূল কংগ্রেসের
167.78 - 169.62: যে সমস্ত নেতারা, বিশেষত সাংসাদরা
169.62 - 171.58: এনসিপিআইতে যোগ দিয়েছেন, যে সমস্ত
171.58 - 172.94: বিধায়করা আলাদা �
184.17 - 185.77: চার্য বিধানসভা ও দিবেশনের মধ্যে
185.77 - 187.59: অভ্যন্তরে দাঁড়িয়ে বিরোধী দলা নেতাকে
187.59 - 189.07: ঐ প্রসঙ্গ নিয়ে কঠাক্ষ কোণতে
189.07 - 203.88: সোনা গিয়েছ ফলে সেই ঘটনার
203.88 - 206.16: প্রক্রম তার রেশ টানুতেকে আজিকে
206.16 - 207.82: যেটা বলেছেন ,তাতে এটা পরিষ্কার
207.82 - 209.88: যে বক্তব্য তিনি রেখেছিলেন বাস্তবের
209.88 - 209.94: �
221.18 - 222.98: এবং তার দলের ভাঙন যে
222.98 - 224.38: পরিমানে বাড়তে শুরু করতে তাতে
224.38 - 226.24: অনেকেই বলছেন, এটাই কাম্য ছিল,
226.34 - 228.12: তবে দুমাস পরে কেন তিনি
228.12 - 228.86: পড়লেন তাতে �
236.89 - 238.65: যিনি আজ কেরে মুক্ষমন্ত্রী হয়েছেন,
238.65 - 240.13: আমার অনেক সুবেচ্ছা থাকবে, কিন্তু
240.13 - 241.27: এটা আর মেনিস্ত্রেই বলব না,
241.31 - 242.77: যে আপনি মুক্ষমন্ত�

Transcription & Chunking took 9.44 seconds
Total chunks generated: 50


Transcribing Dengue with Faster-whisper-large-v3-bn...
Streaming Chunked Output:
0.00 - 2.38: ভারতে প্রথমবার আসছে ডেঙ্গি ভ্যাকসিন,
2.48 - 5.26: কিউ ডেঙ্গা ভ্যাকসিন বাণিজ্যিকভাবে বিক্রির
5.26 - 7.12: অনুমোদন দিল ড্রাগ কন্ট্রল
15.00 - 17.06: বছর বছর বর্ষায়লে এই রাজ্যে
17.06 - 18.76: বাড়ে ডেঙ্গির প্রকম, প্রতি বছর
18.76 - 20.74: মসাবাহিত রোগে আক্রান্ত হন হাজার
20.74 - 33.27: হাজার মাবুষ, সেই লড়াইয় জাপানীর
33.27 - 35.25: তাকে তাঁব বায়োভানমাসিকানসে তৈরি এই
35.25 - 37.11: ভ্যাকসিন চার থেকে সাত বছর
37.11 - 39.31: বর্ষীদের দেওয়া হবে।সমস্থা তাবি, এই
39.31 - 52.48: ভ্যাকসিন  দুবার ডেঙ্গু হয়ে
52.48 - 55.24: গেলে, মানুষ ডেঙ্গু ইমিউন হয়ে
55.24 - 57.88: যায়। তো সেটা যদি আর্টিফিশিয়ালি
57.88 - 60.94: একটা ইনফেকশনের মতন করে দিতে
60.94 - 63.44: পারি, �
69.12 - 71.60: যে এই ডেঙ্গু ভ্যাকসিনটা ইস
71.60 - 74.52: কয়েট সেফ অ্যান্ড এফেকটিভ। -প্রসুক
74.52 - 76.50: কায়ে সমস্থান দাবি ডেঙ্গী ভাইরাসের
76.50 - 77.46: চারটি সেরোটাইপে
83.26 - 85.16: যে প্যাশিন্ট আগেই দিয়ে মেগেই
85.16 - 87.20: ইনফেকটের ছিল কি ছিল না,
87.52 - 90.28: অ্যান্টিবডি আছে কি নেই, স্টেরেট
90.28 - 99.39: ভ্যাকসিন তা দিয়ে দেওয়া যা
99.39 - 101.17: যে একটা ভ্যাকসিন দিলে, যদি
101.17 - 103.63: এখানে আমাদের দুটো ভ্যাকসিন দিত
103.63 - 106.85: হবে, প্রথম ভ্যাকসিন, তিন ভুঁখাসপরে
106.85 - 117.43: আবার সেক্যান্ড ভ্যাকস� আটটির বেশি
117.43 - 119.35: দেশে, অন্তত অটাস আদার মানুষির
119.35 - 121.21: উপর চালনা হয়, ক্লিনিকাল ট্রায়াল,
121.25 - 123.79: ভারতে সফলভাবে ফেস থ্রি ট্রায়ালও
123.79 - 124.21: সম্পন্�
134.11 - 135.51: দেঙ্গির ভ্যাকসিন নিয়েও আলোচন হবে,
135.55 - 136.99: কিন্তু তা জানুয়ারি -ফেব্রুয়ারি মাসের
136.99 - 138.43: আগে পাবেন না আপনারা, তো
138.43 - 139.61: সেই সমাম্যা করব এ�
148.43 - 150.33: বর্ষার মর্সমে দেঙ্গি ও অন্যান্য
150.33 - 152.11: ভেক্টর -বাহিত রোগের সম্প্রমণ রুকতে
152.11 - 153.27: তৎপত প্রশাসন.
153.33 - 173.41: মঙ্গলপাল স্বাস্থ্য সচিব স্বাস�

Transcription & Chunking took 7.45 seconds
Total chunks generated: 39


Transcribing Terrorist(Long) with Faster-whisper-large-v3-bn...
Streaming Chunked Output:
22.00 - 25.76: জঙ্গি, এই নামটা শুনলেই প্রথম
25.76 - 29.08: পাকিস্তানের কথা মাথায় আসে। হ্যাঁ,
29.08 - 32.66: পাকিস্তান ছাড়া গোটা বিশ্বে জঙ্গি
32.66 - 34.92: বা জঙ্গি দেশ বলতে আর
34.92 - 38.46: কেউ নি।পাকিস্তান হচ্ছে জঙ্গিদের আঁতুর
38.46 - 40.46: ঘর।আমরা জানি যে এই ভারতকে
40.46 - 41.94: বার বার রক্তাক্ত করেছে
47.13 - 49.35: কাশ্মীর সংলগ্ন যে রাজ্যগুলি রয়েছে,
49.39 - 51.73: বিশেষ করে উত্তর ভারত এবং
51.73 - 54.39: কিছুটা উত্তর -পূর্ব ভারতকে অশান্ত
54.39 - 55.35: করার চেষ্টা করে
64.33 - 67.09: বাংলাতে ঘাঁটি গেরে বসে থাকছে,
67.23 - 70.33: শুধু তাই নায়, এ রাজ্যের
70.33 - 73.71: মুখ্যমন্ত্রের সুবেন্দু অধিকারীকেও হত্যার পরিকল্পনা
73.71 - 83.29: করছে, ভ বেঙ্গল এসটিএফের নজরে
83.29 - 87.01: এই মুহুর্তে হামিম্বন্ডল, বাংলায় ঘাঁটি
87.01 - 90.01: ঘেরে থাকা এই জঙ্গির একাধিক
90.01 - 92.27: তথ্য এখন গোয়েন্ডাদের হাত�
96.21 - 100.27: এই হামিম মণ্ডল আম জনতার
100.27 - 102.09: মতো মিশে থাকত সাধারণ মানুষের
102.09 - 105.29: সঙ্গে তার নেটওয়ার্ক পাকিস্তান পর্যন্ত।
105.29 - 113.55: আর এই মুহুর্তে আপনাদে রেনেসা
113.55 - 116.45: টাউনশিপ, সেই রেনেসা টাউনশিপের ঠিক
116.45 - 118.83: ম্যাপটা যদি বোঝানোর চেষ্টা করি,
118.87 - 120.43: কেন ম্যাপটা বোঝানোর চেষ্টা করছি,
120.47 - 132.42: কারণ এই  পাশেই দুটো
132.42 - 135.62: স্কুল রয়েছে, যাতে বড় নাশকতা
135.62 - 137.24: ঘটালে এই স্কুলকে বেছিনে যাতে
137.24 - 139.46: পারে, শপিং মল অর্থাৎ বড়
139.46 - 140.78: নাশকতা, বেশি মানুষ জ�
154.94 - 157.98: সবচেয়ে বড় কথা বর্ধমানের খাগড়াগড়,
158.08 - 160.66: যে খাগড়াগড় বিস্ফোরণের পর এনায়
160.66 - 162.56: তদন্তে উঠে এসেছিল জঙ্গি মডিউল,
162.66 - 173.47: জেশ জঙ্গি মডি তার পেছনে
173.47 - 176.65: কি বড় কোন নাশকতার পরিকল্পনা
176.65 - 179.17: ছিল আর এই জন্য মানুষের
179.17 - 182.17: সঙ্গে মিশে থাকত এই জঙ্গীরা।
190.30 - 192.16: মনে করুন আপনি জিমে শরীর
192.16 - 194.44: চর্চা করছেন, কিংবা সবজির বাজারে
194.44 - 197.74: সবজির দরদাম করছেন, ঘুনাকখড়েও টেন্ট
197.74 - 199.26: পারছেন না আপনার পাশেই দ্�
204.76 - 206.72: তেমনই বোঝার উপায় ছিল না,
206.80 - 209.62: সে আএসআই নিযুক্ত নৃশংস জঙ্গি
209.62 - 213.14: সংগঠন জেসের সদস্য।পরিচয় লুকতে কখনও
213.14 - 215.18: সে দরজির কাজ করত, বর্ধমান
215.18 - 215.18:
229.39 - 236.29: বর্ধমান শহর থেকে হাওড়ার পিলখানা।বাংলায়
236.29 - 238.77: ক্ষমতা এসেই অনুপ্রবেশকারী আটকাতে সীমান্তে
238.77 - 256.91: বেড়া দিতে জমি দিয়েছেন বিএসএ
259.29 - 261.69: কোনও ঘিঞ্জি শহর বা এলাকায়
261.69 - 264.47: কোনও অপারেশনের আগে জঙ্গীরা সাধারণত
264.47 - 266.53: মানুষের মধ্যে মিশে থাকে, এটা
266.53 - 278.65: জঙ্গীদের চিরাচরিত প্যা� হাওডার পিলখানা
278.65 - 281.27: অত্যন্ত জনবহুল একটি এলাকা।এই অঞ্চলে
281.27 - 284.39: বেশি সংখ্যালঘুধেরী বসবাস।সেখানেই একটি গেঞ্জি
284.39 - 285.35: কারখানায় কাজ করত
308.00 - 310.16: তখন স্বদ্ধ মন্ত্রী হয়েছেন উত্তর
310.16 - 312.56: হাওড়ার বিজাইপি বিধায়ক উমেশ রায়ী।প্রতিদিন
312.56 - 314.06: প্রচুর ফোন আসছে তার মধ্যে
314.06 - 324.91: একটি ফোন ক বিজেপি অফিসের
324.91 - 326.13: ছবি পাঠিয়ে হামলা রুম কিও
326.13 - 326.55: দেওয়া হয়?
339.64 - 355.48: আমার মনে চিয়ে তারই পরিণামেটায়।
373.31 - 376.23: এরপরই গ্রেপ্তার পাক মদদপুষ্ণ জঙ্গী
376.23 - 378.63: হামিম, ধৃতের বারি বর্ধমানের মন্তেশ্বরের
378.63 - 383.91: কুসুম গ্রামে।বেরো রেপোর্ট যী চব্বি
385.47 - 387.83: আরেকটু তথ্য দালাস, আরেকটু বিশ্লেষণের
387.83 - 389.27: জন্য আমাদের দুই প্রতিনিধি আমাদের
389.27 - 390.69: সঙ্গে এই মুর্তে রয়েছেন, দেবব্রত
390.69 - 391.11: রয়েছেন
403.72 - 405.02: তুনি একটু দেবভ্রতের কাছে চলে
405.02 - 406.88: যাব, দেবভ্রত, হাওড়ার পিলখানা একটা
406.88 - 409.84: অত্যন্ত ঘিনজি এলাকা, সেই ঘিনজি
409.84 - 411.78: এলাকাতেই কি আত্মগোপন�
418.98 - 420.98: তার আমনটাই বলে করা হচ্ছে
420.98 - 422.90: তার কারণ হাওড়ার পীলখানা একেবার
422.90 - 425.38: অত্যন্ত ঘিন্জি এলাকা এখানে সংখ্যালঘু
425.38 - 426.50: সম্প্রদায়ন মালযোজন �
437.87 - 439.85: ধরে দরজির কাজ করতো এবং
439.85 - 441.43: এখানে ঘর ভাড়া নিয়ে থাকতো
441.43 - 443.03: এই আমনটাই আবরা জানতে পাচ্ছে
443.03 - 444.75: পুলিশ সূত্রে এবং এখান থেকে
444.75 - 456.68: বসাই সক্রি� অপারেশন চালিয়ে ছিল
456.68 - 458.36: বাকীকী ধরনের শক অশাহ ছিল,
458.36 - 460.02: সমস্থরাই তাকে জিজ্ঞাসাবাদ করে দেখা
460.02 - 462.18: হচ্ছে, এটি অত্যন্ত চাঞ্চান্নকার অ�
474.44 - 478.12: এবং তারমানে এই ভুলতাই কার্যতঃ
478.12 - 480.60: পুলিসকে পৌঁছে দিল এই হামিম
480.60 - 482.60: পর্যন্ত আমি একটু চলে যাবো
482.60 - 484.20: আমাদের প্রতিনিধির অয়ন সন্মা
488.94 - 491.40: সেখানেই কার্যতক ঘাঁটি গেড়েছে এবং
491.40 - 493.18: তার লোকেশনগুলো যদি আমরা দেখি
493.18 - 494.98: খাগড়াঘর কাছে, জাতীয় সড়ক কাছে,
495.06 - 497.96: স্কুল কাছে কেন বর্
508.54 - 510.34: দেখাও, তোমাকে বলে নেখি, তুমি
510.34 - 512.48: যানও যেন নিউটাউনের সাপর্যীতে যে
512.48 - 514.26: আবাসন রয়েছে, সেটাও কিন্তু বিশল
514.26 - 526.42: একটা জায়গা জুড়ে একটা
533.57 - 536.29: একারে যে জিমে আসতেন তিনি
536.29 - 538.17: জিমে যিনি মালিক তার একটা
538.17 - 539.97: কিছু দক্ষমেতে আমি দেখায়। আমার
539.97 - 541.65: হাতে যেটা রয়েছে, গাইডলাইন গেয়েছে
541.65 - 544.13: তাকো, সেই গাইডলাইন একটো ভেরিফিকেশনের
544.13 - 557.78: যে প্রসেস, সেই ভেরিফিকেশনের প্রসে
557.77 - 560.11: এবং পাশাপাশি একটা রেজিস্টার দেখায়,
560.11 - 562.09: যে রেজিস্টার, এটা কৃষের রেজিস্টার,
562.47 - 564.03: যে জিমে আসত এক মাসের
564.03 - 565.43: জন্য জিমে এসেছিল, আমিম �
570.35 - 572.83: সেই রেজিস্টার সে এসেছিল আজবার,
572.83 - 574.41: এবং জীবের যিনি মালিক রয়েছেন,
574.41 - 576.69: এই যে হামি বন্ডল, তা
576.69 - 578.81: সে কি ডকোমেন্স দিয়েছিল আপনার
578.81 - 590.12: দের  সেখানে কিন্তু পুলিস
590.12 - 592.52: ভেরিফিকেশন করিয়া তাকে কিন্তু রেন্টে
592.52 - 594.60: দিয়া তেকে যখন উনি এখনে
594.60 - 611.44: অ্যাডমিসন করতে এস্টছিলেন তখন উনি
611.34 - 613.12: তারপর সেই নেক্স দিন কবই
613.12 - 613.94: এসবে, সেই দিন তার আছে?
613.96 - 615.42: না, সেই দিনটা, সেই দিনটা
615.42 - 620.06: আমি জানিও না, সেই ম্যাক্সিমাম
620.06 - 629.81: হয়েতে এখানে তিন - দেখে
629.81 - 631.33: দেখে মনে হচ্ছল, তার যে
631.33 - 633.21: আচার ব্যবহার দেখে মনে হচ্ছল
633.21 - 633.35: কান?
633.35 - 635.31: না না, আমি বারবার আপনাদেরকে
635.31 - 637.47: বসছি, মানে উনার আচার, উনার
647.51 - 650.07: দেখে, কেনকে যখন আমরা নোটিস
650.07 - 651.25: করলাম কে এই ছেলেটা আমি
651.25 - 652.99: তো দেখেছি একবার জিমে, তোহানে
652.99 - 653.99: বলে, এই ছেলেটা এরকহম করতে
653.99 - 654.31: পারে, তোহ�
678.66 - 680.38: সাধারণত যারা জঙ্গি হয়, তারা
680.38 - 681.96: কম কথা বলে কম মেলামেশা
681.96 - 684.10: করে, তাদের বাইরের জগদের সঙ্গে
684.10 - 686.52: মেলামেশা কম, কারণ তারা বহির
686.52 - 687.12: জগদের সঙ
693.44 - 695.24: আমি প্রথমে দু -তিনটি কথা
695.24 - 698.44: বলি, যারা দর্শকরা দেখছেন, সবাই
698.44 - 700.76: মনে করবেন যে এজেন্সিরা কেন
700.76 - 702.36: ধরতে পারে, কীরম করে ধরতে
702.36 - 702.82: পারে, অথব�
711.23 - 714.13: একটা পিলখানা হাওড়ায় ঘুবে বেলাছে
714.13 - 716.45: সেখানে, ও একচুলি তৈরি করত,
716.47 - 720.63: গেঞ্জি দোকানে বার কোট, তারপর
720.63 - 721.87: সেখানে দিকে রাজার হাট,
727.93 - 734.83: রেনেসা রেনেসা রেনেসা রেনেসা রেনেসা
734.83 - 740.95: রেনেসা রেনেসা রেনেসা রেনেসা রেনেসা
740.95 - 743.21: রেনেসা রেনেসা রেনেসা রেনেসা রেনেসা
742.75 - 745.57: যে এজেন্সিস, এক্সটার্নাল অথবা ইন্টার্নাল,
745.59 - 748.17: আইভি, রিসার্চ অ্যান্ড অ্যানালিসিস রিং,
748.23 - 750.57: তারা কিন্তু মনিটার করছে এর
750.57 - 751.05: মুভমেন�
758.51 - 760.21: কারণ তাকে বাড়তে দেয়া হয়
760.21 - 763.55: তার মডেল কি, তার টেম্পলেট
763.55 - 765.89: কি, কে কেউর সঙ্গে যোগাযোগ
765.89 - 768.43: রাচ্ছে, কে ওকে লজিস্টিক্স পৌঁছে
768.43 - 779.48: দি� আরাকটা আমি আপনার ঝির
779.48 - 781.38: মধ্যে দিয়ে বলতে চাই, যে
781.38 - 784.06: যেমন আমনা তেরাকি, তালিবান, পাকিস্তান
784.06 - 787.18: শুনেছি, একটা নোত সংস্থা, সংগঠন,
787.22 - 787.56: ভারত
805.74 - 807.28: তো ওটা বিভিন্নই ছোটো ছোটো
807.28 - 809.08: সংগতম করে তাদের - এই
809.08 - 810.42: যে কথাটা আপনি বললেন, কলেন,
810.42 - 811.74: দীপতাংশ চৌধুরী, আপনার কাছে আমি
811.74 - 812.66: যাবো এই প্রসঙ�
833.98 - 835.18: আতুর উপত্যা আমি দেখে বুস্তবাদ
835.18 - 836.32: তো নে চুপচা বাস্ত ব্যামেকর্ত
836.32 - 837.94: চলে এতো মানে চুপচা বাস্ত
837.94 - 839.02: কারও সাথে কোনো কথা বলতো
839.02 - 840.56: করে চ
849.08 - 851.46: যে যদি মানে লুকি চুরিয়া
851.46 - 852.42: আসতে যাসে, তো আমাদের মতে
852.42 - 853.72: নর্মালি অ্যাক্ট করবে, সেখানে তো
853.72 - 873.06: আমি মানে সাসপিসিয়স লিখিতে দেখতে
872.84 - 875.52: এবং শাহজাদ -ভাট্টি, এই দুই
875.52 - 878.46: নেটওয়ার্কের সঙ্গে কানেকশান, লরেন্স বিষ্ণয়
878.46 - 880.94: গাঘের সঙ্গে কানেকশান, জাইসিম আহমদের
880.94 - 892.20: সঙ্গে ক হামিম কি এই
892.20 - 894.36: ধরনের কোন খুন বা ছোট
894.36 - 896.92: কোন এক্সপ্লোসন করার পরিকল্পনা করছিল?
898.94 - 901.42: সৈকিবাদ একদম করেক্ট এই লোকগুলোকে
901.42 - 909.33: ছেড়ে রাখা হ ঘন বসতি
909.33 - 911.69: সেই সব জায়গায় থাকে, সেখান
911.69 - 913.79: দিকে ওরা রিক্রুটিং করে এবং
913.79 - 917.85: তারা থুর সোশাল মিডিয়া, অনেকগুলো
917.85 - 921.89: ক্লোজ নেট সোশাল মিডি�
924.51 - 926.17: ধরন স্বামীন মন্দল যাকে আলাও
926.17 - 928.25: করবে, এবং তার থেকে, সবাই
928.25 - 929.49: কেন আসবে, তার থেকে কিছু
929.49 - 932.13: আর্থিক, বিনয়কভাবে, আর্থিকভাবে সাহায্য �
942.14 - 944.66: সাহায্য করে তারা আকৃষ্ট হবে,
944.70 - 946.66: তারা সামনে আসবে, এই করে
946.66 - 949.28: তাদের নেটওয়ার্কটা বাড়ায়, এবং এর
949.28 - 952.14: সাথে সাথে যে তার হ্যানলার,
952.14 - 955.66: স�
957.82 - 959.76: এখানের অবজেক্ট ছিল একটা হাই
959.76 - 962.36: ভ্যালু টার্গের, কে ছিল, মুক্তমন্ত্রী
962.36 - 964.54: সুবেন্দু অধিকারী হত্যা করার জন্য
964.54 - 974.44: একটা প্ল্যান প্ মুখ্যমন্ত্রী মহাসায়ের
974.44 - 977.12: বাড়ির কাছে তার মুভমেন্ট দেখছিল,
977.32 - 980.36: তার যে ছোটা মোবাইল পাওয়া
980.36 - 982.42: গেছে, যা ইলেকট্রনিক এভিডেন্স পা�
990.24 - 992.04: কজন তার সিকিউরিটি ডিটেলে রোগ
992.04 - 994.38: তাকে কি ভাবে থাকে, তার
994.38 - 997.10: ছবি ল্যাপটপ থেকে কাকে পাঠাচ্ছে,
997.12 - 999.90: এবং তার যে টাকাপর্তর আচ্ছে,
1007.26 - 1008.88: মোবাইলে অনেকভাবে আমি ডিলিট করে
1008.88 - 1010.66: হত বেচেছে, কোনটা ভাজবে না,
1010.70 - 1013.44: এভরিথিং একবার যদি ইলেকট্রনিক এভিডেন্স
1013.44 - 1017.18: চলে আসে, একবার যদি
1021.90 - 1023.94: বর্তাদ সব মিলে যেটা পরিষ্কার
1023.94 - 1025.54: বোঝা যাচ্ছে যে আপাতত যা
1025.54 - 1028.00: তথ্য সামনে আসছে তাতে হামিম
1028.00 - 1029.84: মণ্ডলের নেটওয়ার্কে সূত্র ধরে আ�
1048.10 - 1050.60: আমরা জানতাম যে এই জাতির
1050.60 - 1052.76: একটা প্রচেষ্ট আরে হবে, এটা
1052.76 - 1055.14: স্বাভাবিকভাবে জানতাম কিংদামি সঙ্গে সঙ্গে
1055.14 - 1056.34: গোয়েন্দ্র জপ্তর এবং
1067.31 - 1069.61: অত এখানে কোন মিশনের জন্য
1069.61 - 1072.15: এলে একাএকাত আসেনি, অতেকে মিশনের
1072.15 - 1074.19: সাথে অন্যরা জড়িত আছে, একে
1074.19 - 1076.75: সাথে কোন রাজনৈতিক ব্যক্তিত্ব �
1085.59 - 1089.23: অত্যন্ত দুর্ভাগ্য যেন আমাদের রাজ্যের
1089.23 - 1092.77: এসটিএফ তার ধরেছে এইরা নিরামত্তা
1092.77 - 1094.61: সুনিশ্চিত করা হোক আমরা আশা
1094.61 - 1097.53: করি এই ধরনের রাষ্�
1104.08 - 1106.14: সেই জন্য এধরনের হয়েতু আমরা
1106.14 - 1109.24: আশা করছি নিশ্চিতভাবে ত্বন্ত হবে
1109.24 - 1115.44: ত্বন্তের সঠিক বিচার নিশ্চিত হবে।
1119.18 - 1121.86: তেকন এটা হবার ছিল, তরলে
1121.86 - 1123.62: আমরাই একমাত্র রাজনৈতিক দল আমরা
1123.62 - 1125.20: আশির দশক থেকে বলে এসেছেন
1125.20 - 1126.56: যে একটা বিনা যুদ্ধে ভারত
1126.56 - 1139.41: দখলের চক্রা� বিভিন্ন জায়গায় শিশু
1139.41 - 1142.35: মনে বিদ্দেশের বিশ, দেশবিন্য দিদার
1142.35 - 1144.67: বিশ, হিন্দু বিদ্দেশের বিশ ঢুকে
1144.67 - 1157.25: দেয়া হয়েছে যে পরিবেশ তৈরি
1157.25 - 1161.08: � মুখো মন্ত্রী নিশ্চিতভাবে তাঁকে
1161.08 - 1163.86: হত্যার টার্গেট করে এলে সেটা
1163.86 - 1167.86: উদ্বেগের নিন্দার, পাশাপাশি এই ধরনের
1167.86 - 1168.96: জঙ্গি সংগঠনগুলো
1171.10 - 1173.02: যেখানে সেখানে বোমাবিস পূরণ, আমনা
1173.02 - 1174.92: তো দেখেছি ভারতবর্ষের বিভিন্ন জায়গায়
1174.92 - 1176.32: সেনা অন্দের মেরে দিয়ে গেল
1176.32 - 1194.08: উপুলোয়ামায়
1197.47 - 1201.05: বাংলার আওয়াজ বাঙালির আবেগ সি
1201.05 - 1201.85: চব্বিশ ঘটা

Transcription & Chunking took 71.15 seconds
Total chunks generated: 248


Transcribing Taslima Nasrin(Long) with Faster-whisper-large-v3-bn...
Streaming Chunked Output:
0.00 - 1.72: আচ্ছা, কী জামতি চেয়েছিলেন?
2.34 - 4.44: জয় গোস্বামী, যামকে আপনি জয়
4.44 - 6.44: গোস্বামীকে ডাকদেন, তুনি স্মৃদী পর্যন্তার
6.44 - 30.00: চলে গেছিলেন, তার তোঁও আর
30.00 - 32.40: আমি আমার যে ভাষণ ছিল,
32.58 - 35.54: সেখানে তোঁও আমি বাকসাধীনতার কথাই
35.54 - 38.50: গলেছিলেন যি আমদের ভিন্ন মত
38.50 - 45.62: থাকতে পারে, কিন্তু কাউ সবাই�
47.74 - 49.66: আমি তো ঠিক যে কথাটাই
49.66 - 53.34: বলেছিলাম, যারা আমার কথা পছন্দ
53.34 - 56.18: করেছিলেন, তাদের মধ্যে কি তারা
56.18 - 59.70: ছিলেন, যারা জয়গর সোমীকে মঞ্চে
59.70 - 67.91: উঠতে একদিকে, একজন যখন মত
67.91 - 71.09: প্রকাশের অধিকারের পক্ষে বলছে, তখন
71.09 - 74.01: তোমরা তাকে সমর্থন করছো, কিন্তু
74.01 - 79.85: মত প্রকাশের অধিকারের জন্য, যখন
83.35 - 87.01: আরেকজন কবিকে ডাকছেন, তুমি তখন
87.01 - 88.71: তার কথার সন্তেক চাইছো না?
89.35 - 91.53: তাহলে তো, আমার তো খারাপ
91.53 - 94.99: লাগবে, আমার লেগেছে, এবং আশা
94.99 - 97.85: করি, এইরকম অবস্থা আর হবে
97.85 - 100.91: না, কারণ কলকাতা প্রভতীশীলদের শহর,
100.99 - 105.09: এখানে সবাই বাকসাধিনাতা এবং মারপ্রকাশের
105.09 - 110.61: অধিকারে বিশ্বাস করেন বল�
113.13 - 116.31: ভিন্ন হতে পারে, কিন্তু সবারই
116.31 - 119.09: তার ভিন্ন মত প্রকাশ করার
119.09 - 122.29: অধিকার থাকতে হাবে।
137.84 - 140.22: আজকে না কথা হয়নি, কিন্তু
140.22 - 141.20: আমি কথা বলবো,
143.16 - 151.56: এটা শুধু আমি আঁচ বা
151.56 - 154.08: কাল আমি যাব তার বাড়িরটি
154.08 - 155.24: কথা বস্তে।
168.63 - 176.57: এই পার্থক্য তো আছেই, এক
176.57 - 179.63: সরকার আমাকে বের করে দিয়েছিলেন,
179.71 - 182.29: দ্বিতীয় সরকার আমাকে আসতে দেন
182.29 - 182.57: নি।
186.28 - 190.96: আসতে দিয়েছেন তিনটি পার্থক্যতা আছেন
190.96 - 194.00: এখন সেই পার্থক্যটা না দেখে
194.00 - 199.20: এইটাই আসতে পারলাম সেটাই আমের
199.20 - 200.46: মনে সেলেপ্রেট করা উ�
204.27 - 206.59: যে আমি আসতে পেরেছি এবং
206.59 - 209.23: শুধু আমি বিশ্বাস করতে চাই
209.23 - 211.01: যে এই সরকার মত প্রকাশের
211.01 - 213.65: অধিকারে বিশ্বাস করেন, এই সরকার
213.65 - 214.41: বাক্স আধীনতা�
221.61 - 225.45: প্রকাশ করলেও, আমি এখানে এই

,Video,WER %,CER %,Word Accuracy %,GT Words,Pred Words,Correct Words,Substitutions,Deletions (Missed),Insertions
0,Rain,70.70,60.75,29.77,215,89,64,24,127,1
1,Delhi Protest,63.98,52.34,37.10,186,94,69,23,94,2
2,Subhendu CM,74.76,66.82,25.56,626,233,160,71,395,2
3,Dengue,70.05,57.35,31.04,364,178,113,61,190,4
4,Terrorist(Long),69.57,58.17,31.14,2527,1164,787,359,1381,18
5,Taslima Nasrin(Long),61.91,49.23,39.29,2670,1491,1049,410,1211,32
6,Shamik(Long),72.19,59.64,28.46,2625,1161,747,397,1481,17
7,10am News(Long),70.56,60.12,30.01,2456,1070,737,319,1400,14

### Faster-whisper-tugstugi

In [2]:
from faster_whisper import WhisperModel, BatchedInferencePipeline

model = WhisperModel("models\\tugstugi_ct2_float16", device="cuda", compute_type="float16")

batched_model = BatchedInferencePipeline(model=model)

print("Loaded batched model successfully")

Loaded batched model successfully

In [4]:
run_transcription(
    batched_model=batched_model,
    model_name="Faster-whisper-tugstugi",
    language='bn',
    vad_parameters={"min_silence_duration_ms": 4000, "speech_pad_ms": 5000}
)

Transcribing Rain with Faster-whisper-tugstugi...
Streaming Chunked Output:
0.00 - 2.20: দক্ষিণবঙ্গে আজ ও কাল ভারী
2.20 - 4.54: বৃষ্টির সম্ভাবনা কলকাতায় দফায় দফায়
4.54 - 6.86: বৃষ্টির সম্ভাবনা থাকছে। শুক্রবার থেকে
6.86 - 9.24: এই বৃষ্টি কমবে কলকাতায়। দুই
9.24 - 10.90: চব্বিশ পরগনায় ভারী বৃষ্টির হলুদ
10.90 - 12.66: সতর্কতা রয়েছে। ভারী বৃষ্টির সতর্কতা
12.66 - 15.40: থাকছে পূর্ব মেদিনীপুর, পশ্চিম বর্ধমান
15.40 - 19.14: বাঁকুড়াতেও। অন্য জেলাতেও বিক্ষিপ্ত দু
19.14 - 21.60: এক ফসলা বৃষ্টির সম্ভাবনা থাকছে।
21.60 - 24.66: শনি এবং রবিবার দক্ষিণবঙ্গে বৃষ্টির
24.66 - 29.18: পরিমাণ কমবে। আর অন্যদিকে উত্তরবঙ্গে
29.18 - 34.50: আগামীকাল থেকে বৃষ্টির পরিমাণ কমবে।
34.50 - 36.28: অয়ন ঘোষাল আমাদের প্রতিনিধিরে অইছেন
36.28 - 37.56: আমাদের সঙ্গে অয়ন সব মিলিয়ে
37.56 - 39.30: কি পূর্বাভাস হাওয়া অফিসে।
43.93 - 46.79: এই মুহূর্তে মৌসুমী অক্ষরেখা মুর্শিদাবাদ
46.79 - 49.47: থেকে গাঙ্গেয় দক্ষিণবঙ্গের প্রায় ওপোট
49.47 - 51.53: দিয়ে বাংলাদেশ পর্যন্ত বিস্তৃত সেই
51.53 - 53.49: মৌসুমী অক্ষরেখার হাত ধরে যে
53.49 - 55.11: বৃষ্টি গতকাল থেকি শুরু হয়েছে
55.11 - 56.79: সেই বৃষ্টি আজ বুধবার এবং
56.79 - 59.83: আগামীকাল বৃহস্পতিবার পর্যন্ত কোরা দক্ষিণবঙ্গি
59.83 - 62.23: তার দাপট দেখাবে। বৃষ্টির সঙ্গে
62.43 - 64.13: তিরিশ থেকে চল্লিশ কিলোমিটার বেগে
64.13 - 66.33: ধমকা ঝোড়ো হাওয়ার পূর্বাভাস রয়েছে।
66.33 - 68.45: উপকূলের জেলার ক্ষেত্রে এই ধমকা
68.45 - 70.23: ঝোড়ো হাওয়ার গতিবেগ কোনো কোনো
70.23 - 72.27: জায়গায় পঞ্চাশ কিলোমিটার পর্যন্ত হতে
72.27 - 75.09: পারে। উপকূল এলাকাতে বৃষ্টিপাতের পরিমাণ
75.09 - 77.17: গাঙ্গেয় দক্ষিণবঙ্গের থেকে বেশি থাকবে।
77.40 - 79.78: এই অবস্থা বৃহস্পতিবার পর্যন্ত চলার
79.78 - 81.94: পর শুক্র, শনি এবং রবি
81.94 - 84.84: উত্তর এবং দক্ষিণবঙ্গে লক্ষণীয়ভাবে বৃষ্টিপাতের
84.84 - 88.00: পরিমাণ কমবে। উত্তরবঙ্গে বৃহস্পতিবারের পর
88.00 - 90.14: এবং দক্ষিণবঙ্গে শুক্রবারের পর থেকে
90.14 - 91.96: কমে যাওয়া বৃষ্টি। নতুন করে
91.96 - 94.12: উত্তরবঙ্গে মঙ্গলবারের পর থেকে বৃষ্টি
94.12 - 96.60: বাড়ার সম্ভাবনা দক্ষিণবঙ্গের ক্ষেত্রে আগামী
96.60 - 98.92: বুধবার বৃহস্পতিবার থেকে ঝড় এবং
98.92 - 103.12: বৃষ্টির আর
108.15 - 112.31: বাংলার আওয়াজ বাঙালির আবেগ জি
112.31 - 113.45: চব্বিশ ঘন্টা।

Transcription & Chunking took 3.08 seconds
Total chunks generated: 42


Transcribing Delhi Protest with Faster-whisper-tugstugi...
Streaming Chunked Output:
0.00 - 8.48: মাতির সরকার। ছাত্রদের আন্দোলনে উত্তপ্ত
8.48 - 11.12: হয়ে উঠেছে ভারতের রাজধানী নয়াদিল্লি।
11.12 - 13.74: নয়াদিল্লিতে মেডিকেল ভর্তি পরীক্ষা সংক্রান্ত
13.74 - 19.42: প্রশ্নফাঁস ও অন। গতকাল সোমবার
19.42 - 21.86: বিশ জুলাই সংসদের বর্ষাকালীন অধিবেশন
21.86 - 24.66: চলাকালে ককরোজ জনতা পার্টির ব্যানারে
24.72 - 27.56: হাজারো আন্দোলনকারী নিরাপত্তা বেরিকেট ভেঙ্গে
27.56 - 29.48: সংসদ ভবনের মূল ফটকের দিকে
29.48 - 36.44: অগ্রসর হন। এসময় ভবনের ভেতরেই
36.44 - 39.86: প্রধানমন্ত্রী উপস্থিত ছিলেন। পরিস্থিতি ক্রমশ
39.86 - 42.12: উত্তপ্ত হয়ে উঠলে ও বিক্ষোভকারীদের
42.12 - 44.40: সাথে পুলিশের দফায় দফায় সংঘর্ষ
44.40 - 45.06: শুরু হলে
48.95 - 52.03: শিক্ষার্থীদের আন্দোলনে পুলিশের ব্যাপক লাঠিচার্জ
52.03 - 54.33: এবং রাবার বুলেট নিক্ষেপের পর
54.33 - 56.89: এই আন্দোলন এখন।
65.33 - 67.55: মে মাসে যাত্রা শুরু করার
67.55 - 69.71: পর থেকে সিজেপি সোশ্যাল মিডিয়ায়
69.71 - 72.01: লক্ষ লক্ষ অনুসারী অর্জন করেছে
72.01 - 74.19: যা দুই হাজার চব্বিশ সালে
74.19 - 76.33: তৃতীয়বারের মতো ক্ষমতায় আসার পর
76.33 - 79.75: থেকে হিন্দু জাতীয়তাবাদী প্রধানমন্ত্রী নরেন্দ্র
79.75 - 81.85: মোদীর জন্য অন্যতম বড় চ্যালেঞ্জ
81.85 - 82.63: তৈরি করেছে।
83.96 - 86.80: সিজেপির আশুতোষ একটি সোশ্যাল মিডিয়া
86.80 - 89.36: পোস্টে বলেছেন আমরা থামবো না।
89.36 - 93.54: প্রধানকে বরখাস্ত করতেই হবে। মঙ্গলবারও
93.54 - 95.82: শত শত বিক্ষোভকারী যন্ত্র মন্ত্ররের
95.82 - 98.96: প্রতিবাদিস্থলে অবস্থান করছেন। যাদের অনেকেই
98.96 - 102.08: শিক্ষাব্যবস্থায় ব্যাপক পরিবর্তনের আহ্বান জানাচ্ছিলেন।
108.68 - 110.94: সোমবার প্রায় পাঁচ বছরের মধ্যে
110.94 - 113.50: দিল্লির অন্যতম বৃহত্তম এক জনসমাবেশে
113.50 - 116.24: বিক্ষোভকারীদের সংসদ অভিমুখে মিছিল করতে
116.24 - 117.92: বাধা দিতে পুলিশ কাদানে গ্যাস
117.92 - 120.00: ও লাঠিচার্জ করে। বলে জানা
120.00 - 123.24: গ্যাছে। বিক্ষোভের আয়োজকরা কর্তৃপক্ষের এই
123.24 - 125.60: একনায়ক সুলভ আচরণের নিন্দা করেছেন
125.60 - 127.96: এবং বলেছেন যে শত শত
127.96 - 130.22: বিক্ষোভকারী আহত হয়েছেন।

Transcription & Chunking took 2.71 seconds
Total chunks generated: 39


Transcribing Subhendu CM with Faster-whisper-tugstugi...
Streaming Chunked Output:
0.00 - 3.36: মমতা বন্দ্যোপাধ্যায় যে হেরে গিয়েছেন
3.36 - 5.36: সেটাই কার্যত মেনে নিচ্ছিলেন না
5.36 - 7.92: মমতা বন্দ্যোপাধ্যায়। কিন্তু না, অবশেষে
7.92 - 10.88: শুভেন্দু অধিকারিকে মুখ্যমন্ত্রী হিসেবে মেনে
10.88 - 13.24: নিলেন মমতা বন্দ্যোপাধ্যায়। গতকাল ফেসবুক
13.24 - 14.86: লাইভ করলেন সেখানে অনেক কিছু
14.86 - 16.56: বললেন আর তার মধ্যেই দেখা
16.56 - 20.34: গেলো অবশেষে শুভেন্দু অধিকারিকে মুখ্যমন্ত্রী
20.34 - 26.01: মানলে মতা বন্দোপাধ্যায়। যিনি আজকে
26.01 - 27.77: মুখ্যমন্ত্রী হয়েছেন আমার অনেক শুভেচ্ছা
27.77 - 29.09: থাকবে। কিন্তু এটা আমি নিশ্চয়ই
29.09 - 30.73: বলবো না। যে আপনি মুখ্যমন্ত্রী
30.73 - 33.35: হয়েছেন বলে আপনি তৃণমূলটা করেননি।
33.35 - 35.63: আপনিও কংগ্রেস করতেন একদিন। আপনিও
35.63 - 37.69: নির্বাছনে অনেকবার হেরেছেন। এবং আপনার
37.69 - 39.27: জন্য আমি বারবার যেতাম আপনার
39.27 - 41.28: কেন্দ্রে। সেটা আমার কর্তব্য ছিল।
41.28 - 42.84: এর জন্য আমি কোনো কৃতিত্ব
42.84 - 47.36: নিচ্ছি না। আবির অইছে আমার
47.36 - 48.82: সঙ্গে আবিরের কাছ থেকে জানতে
48.82 - 52.04: চাইবো আবির অবশেষে শুভেন্দুকে মানলেন
52.04 - 52.64: মমতা।
55.96 - 58.52: নাগো চৌঠামের ফল প্রকাশের পর
58.52 - 61.06: মমতা বন্দোপাধ্যায় তিনি রাজভবনেও যাননি
61.06 - 63.20: ইস্তফা দিতে। এমনকি তার পরে
63.20 - 65.00: তিনি যে সাংবাদিক সম্মেলন কালীঘাটের
65.00 - 67.10: বাড়িতে ডেকেছিলেন। সেখানে দাঁড়িয়েও তিনি
67.10 - 68.96: উল্লেখ করেছিলেন বা তিনি যে
68.96 - 70.68: হেরে গেছেন সেটাকে কার্যত স্বীকার
70.68 - 72.54: করেননি। হারিয়ে দেওয়া হয়েছে এমন
72.54 - 74.74: একটা অভিযোগ তিনি করেছিলেন। এবং
74.74 - 75.94: প্রায় দ্বি দীর্ঘ সময় ধরে
75.94 - 77.76: তিনি তার নিজের বক্তব্যের জায়গাতে
77.76 - 79.84: অনড় ছিলেন। একাদিক যারা তৃণমূল
79.84 - 81.84: কংগ্রেসের নেতারা তারা প্রকাশ্যে প্রথম
81.84 - 83.58: দিকে বলতে না পারলেও, পরবর্তী
83.58 - 84.96: সময় তারাও বলতে শুরু করেন
84.96 - 88.50: যে ভূমিকা পালন করা হচ্ছে
88.50 - 90.30: তা যথাযথ ই নয়। হারটাকে
90.30 - 91.58: সহজ করে স্বীকার করে নেওয়া
91.58 - 94.12: উচিত। এবং পরবর্তী সময় তৃণমূল
94.12 - 99.10: কংগ্রেস ভেঙ্গেও যায় এবং ভেঙ্গে
99.10 - 105.80: যা এরে মদ্যে আজকে দেখতে
105.80 - 107.54: পাওয়া গেলো যে সোশ্যাল মিডিয়াতে
107.54 - 108.90: তিনি তার পেজে যে লাইভ
108.90 - 110.76: করেছেন সেই লাইভের মদ্যে তিনি
110.76 - 114.28: কার্যত মুখ্যমন্ত্রী শুভেন্দু অধিকারিকে কার্যত
114.28 - 116.34: তিনি মেনে নিয়েছেন। এবং তার
116.34 - 118.56: কাজের বিষয় সেই বিষয়ের কথাও
118.56 - 120.28: তিনি মনে করিয়ে রেখেছেন। আসলে
120.28 - 121.78: দুমাস পরে তার মেনে নেওয়ার
121.78 - 123.28: বিষয় তাতে মনে করা হচ্ছে
123.28 - 125.33: যে এক তৃণমূল কংগ্রেসের ভাঙন
125.33 - 127.13: প্রায় প্রত্যেক দিনই হয়ে চলেছে।
127.13 - 128.57: এবং এমন একটা সময়ে দাঁড়িয়ে
128.57 - 129.83: তাকি এই কথাগুলা বলতে হচ্ছে
129.83 - 131.55: যখন তৃণমূল কংগ্রেস বলতে যে
131.55 - 133.77: সমস্ত নেতারা পরিচিত ছিলেন মমতা
133.77 - 135.91: বন্দ্যোপাধ্যায়ের পরে তারা ভেঙ্গে বেরিয়ে
135.91 - 137.43: চলে গিয়েছেন এবং তারাও দুশ্যেন
137.43 - 139.73: হচ্ছে তৃণমূল কংগ্রেসের কালীঘাট পন্থী।
139.73 - 141.79: যে কৌশল, রাজনৈতিক কৌশল তাকে
141.79 - 144.10: দাঁড়িয়ে� এবং মমতা বন্দোপাধ্যায় হয়তো
144.10 - 146.40: বুঝতে পেরেছেন যে বাস্তবের এবং
146.40 - 148.48: যে কল্পনার যে মিশেল তার
148.48 - 150.30: দুটার মধ্যে ফারাক কোথায় রয়েছে।
150.30 - 152.28: এবং বর্তমান দিনে দাঁড়িয়ে বাস্তবের
152.28 - 153.94: মাটিতে দাঁড়িয়ে যে ফরিস্থিতি স্বীকার
153.94 - 155.92: তৃণমূল কংগ্রেসের কালীঘাট পন্থী নেতাদেরকে
155.92 - 158.18: হতে হচ্ছে তাতে এখনও পর্যন্ত
158.18 - 159.44: যদি হার স্বীকার না করা
159.44 - 166.60: এবং নতুন মুখ্যমন্ত্রীকে মুখ্যমন্ত এটা
166.60 - 167.94: ঠিক যে তৃণমূল কংগ্রেসের যে
167.94 - 170.30: সমস্ত নেতারা বিশেষত সাংসাদরা এনসিপিআইতে
170.30 - 172.50: যোগ দিয়েছেন, যে সমস্ত বিধায়করা
172.50 - 174.32: আলাদা ব্লক তৈরি করেছেন তারা
174.32 - 177.08: প্রত্যেকেই কখনো না কত কয়েকদিনের
177.08 - 178.66: কথাবার্তার মধ্যে বুঝিয়ে দেবার চেষ্টা
178.66 - 180.70: করেছেন যে বক্তব্য রাখা হয়েছিলো
180.70 - 182.24: হার স্বীকার না করার প্রসঙ্গে
182.24 - 184.04: দাঁড়িয়ে তা ঠিক নয়। এমনকি
184.04 - 186.41: রাজ্য বিধানসভা অধিবেশনের মধ্য তোরে
186.41 - 187.79: দাঁড়িয়ে বিরাধী দলের নেতাকে ওই
187.79 - 189.35: প্রসঙ্গ নিয়ে কটাক্ষ কমতে শুনা
189.35 - 191.93: গিয়েছিলো এবং মুখ্যমন্ত্রীকেও নানাভাবে কটাক্ষ
191.93 - 193.29: করতে দেখতে পাওয়া যায়। এবং
193.29 - 194.43: দুই হাজার একুশ এবং দুই
194.43 - 197.93: হাজার ছাব্বিশ দুটোতেই মমতা বন্দ্যোপাধ্যায়
197.93 - 199.61: শুভেন্দু অধিকারীর কাছে তিনি পরাস্ত
199.61 - 201.25: হয়েছেন। এবং যে শুভেন্দু অধিকারী
201.25 - 202.83: একটা সময় তৃণমূল কংগ্রেসে ছিলে
203.02 - 205.22: ফলে সেই ঘটনার ক্রম তার
205.22 - 206.42: রেশ টানতে গিয়া আজকে যেটা
206.42 - 208.28: বলেছেন তাতে এটা পরিষ্কার যে
208.28 - 210.34: বক্তব্য তিনি রেখেছিলেন বাস্তবের মাটিতে
210.34 - 212.40: দাঁড়িয়ে আজকে সেই বক্তব্যের প্রেক্ষিতে
212.40 - 213.82: দাঁড়িয়ে কুনু ব্যক্তি বিশ্বাস করতে
213.82 - 215.24: চাইবেন না বা এই বাস্তবের
215.24 - 216.60: মাটিতে দাঁড়িয়ে এই রাজনীতিকে এগিয়ে
216.60 - 218.08: নিয়ে যাওয়াটা সম্ভব না। সেই
218.08 - 219.92: কারণেই আজকে তিনি কার্যত স্বীকার
219.92 - 220.80: করে ন
223.18 - 224.46: মানে বাড়তে শুরু করেছে। তাতে
224.46 - 226.50: অনেকেই বলছেন এটাই কাম্য ছিল।
226.50 - 228.28: তবে দুমাস পরে কেন তিনি
228.28 - 229.80: করলেন। তাতে অনেকটা সময় নষ্ট
229.80 - 231.38: হয়েছে এবং তৃণমূল কংগ্রেসের যে
231.38 - 233.70: ভাবমূর্তি ক্ষুন্ন হয়েছে। এটাই অনেকেই
233.70 - 236.66: এই মুহুর্তে বলতে শুরু করেছেন।
236.66 - 238.90: যিনি আজকে মুখ্যমন্ত্রী হয়েছেন আমার
238.90 - 240.36: অনেক শুভেচ্ছা থাকবে। কিন্তু এটা
240.36 - 241.65: আমি নিষ্টুই বলবো না। তে
241.65 - 243.71: আপনি মুখ্যমন্ত্রী হয়েছেন বলে আপনি
243.71 - 244.95: তৃণমূলটা করেননি?
245.05 - 247.33: আপনিও কংগ্রেস করতেন একদিন। আপনিও
247.33 - 249.41: নির্বাছনে অনেকবার হেরেছেন। এবং আপনার
249.41 - 251.01: জন্য আমি বারবার যেতাম আপনার
251.01 - 253.01: কেন্দ্রে। সেটা আমার কর্তব্য ছিল।
253.01 - 254.57: এর জন্য আমি কোনো কৃতিত্ব
254.57 - 255.89: নিচ্ছি না।

Transcription & Chunking took 5.86 seconds
Total chunks generated: 120


Transcribing Dengue with Faster-whisper-tugstugi...
Streaming Chunked Output:
0.00 - 2.70: ভারতে প্রথমবার আসছে ডেঙ্গি ভ্যাকসিন।
2.70 - 5.38: কিউ ডেঙ্গা ভ্যাকসিন বাণিজ্যিকভাবে বিক্রির
5.38 - 7.58: অনুমোদন দিলো ড্রাগ কন্ট্রোল জেনারেল
7.58 - 9.28: অফ ইন্ডিয়া। তবে এই ভ্যাকসিন
9.28 - 10.94: বাজারে আসতে আরও কয়েক মাস
10.94 - 15.16: সময় লাগবে বলে জানিয়েছেন স্বাস্থ্যমন্ত্রী।
15.16 - 16.74: বছর বছর বর্ষা আইলে এই
16.74 - 18.78: রাজ্যে বাড়ে ডেঙ্গির প্রকোপ। প্রতিবছর
18.78 - 20.40: মশা মাহিত রোগে আক্রান্ত হন।
20.40 - 22.58: হাজার হাজার মানুষ। সেই লড়াইয়ে
22.58 - 24.30: এবার নতুন হাতিয়া পেলো দেশ।
24.30 - 25.72: ভারতে প্রথম বা রাস্তা চলেছে
25.72 - 27.90: ডেঙ্গির প্রতিষেধক ভ্যাকসিন। ড্রাগ কাঞ্চল
27.90 - 29.96: জেনারেল অফ ইন্ডিয়া বাণিজ্যিকভাবে ডেঙ্গির
29.96 - 32.12: ভ্যাকসিন কিউ ডেঙ্গা ব্যবহারের অনুমোদন
32.12 - 34.06: দিয়েছে। জাপানির তাঁকে তাঁর বায়ো
34.06 - 34.46: -ফার্মাসি
35.98 - 37.56: চার থেকে ষাট বছর বয়সীদের
37.56 - 39.36: দেওয়া হবে। সংস্থার দাবি এই
39.36 - 41.00: ভ্যাকসিন নেওয়ার জন্য কোনো প্রি
41.00 - 42.68: ভ্যাকসিনেশন স্ক্রিনিং এর প্রয়োজন হবে
42.68 - 44.66: না। অর্থাৎ, আগে কোনো ডেঙ্গি
44.66 - 46.36: হইছে কিনা। তা যাচাই না
46.36 - 48.24: করেও এই টিকা নেওয়া সম্ভব।
48.24 - 51.96: এটা ঠিক যে একবার দুবার
51.96 - 54.54: ডেঙ্গু হয়ে গেলে মানুষ ডেঙ্গু
54.54 - 56.55: ইমিউন হয়ে যায়। তো সেটা
56.55 - 60.23: যদি আমি আর্টিফিশিয়ালি একটা ইনফেকশনের
60.23 - 62.81: মতোন করে দিতে পারি। তাহলে
62.81 - 66.03: আমি ভীষণভাবেই আশাবাদী যে ডেঙ্গুটা
66.03 - 68.19: প্রিভেন্ট করা যাবে। রিসেন্ট স্টাডিসে
68.19 - 70.67: দেখা গেছে যে এই ডেঙ্গু
70.67 - 73.33: ভ্যাকসিনটা ইস কোয়াইট সেফ এন্ড
73.33 - 76.11: এফেক্টিভ। প্রস্তুতকারী সংস্থার দাবি। ডেঙ্গি
76.11 - 78.79: ভাইরাসের চারটি সেরোটাইপের বিরুদ্ধেই সুরক্ষা
78.79 - 80.61: দিতে সক্ষম এই ভ্যাকসিন। আমাগে
80.61 - 82.89: কুনু আগে টেস্ট করতে হচ্ছে
82.89 - 84.77: না। যে প্রেসেন্ট আগে দিয়ে
84.77 - 87.09: ডেঙ্গি ইনফেক্টেড ছিলো কি ছিলো
87.09 - 90.35: না। এন্টিবডি আছে কিনে স্ট্রেট
90.35 - 92.49: ভ্যাকসিনটা দিয়ে দেওয়া যাবে। আমরা
92.49 - 94.23: যে নিমোনিয়ার একটা ভ্যাকসিন এখন
94.23 - 96.23: পেয়েছি। যে একটা দিলেই লাইফটাইম
96.23 - 99.27: হয়ে যাচ্ছে। অনেকটা সেইরকম হলো
99.27 - 101.25: যে একটা ভ্যাকসিন দিলে যদি
101.25 - 103.77: এখানে আমাদের দুটো ভ্যাকসিন দিতো
103.77 - 106.65: হবে। প্রথম ভ্যাকসিন টিম, মাস
106.65 - 109.21: ফরে আবার সেকেন্ড ভ্যাকসিন। কিন্তু
109.21 - 111.11: তাতে আমাদের পুরো খাবার হয়ে।
111.40 - 114.00: ইতিমধ্যেই সুইজারল্যান্ড ইন্দোনেশিয়া, মালয়েশিয়া সহ
114.00 - 116.78: তেতাল্লিশটি দেশে অনুমোদন পেয়েছে কিউটেঙ্গা।
116.78 - 118.84: আটটির বেশি দেশে অন্তত আঠাশ
118.84 - 120.12: হাজার মানুষের উপর চালানো হয়
120.12 - 123.20: ক্লিনিকাল ট্রায়াল। ভারতে সফলভাবে ফেস
123.20 - 125.58: থ্রি ট্রায়ালও সম্পন্ন হয়েছে। কিউটেঙ্গা
125.58 - 127.92: ভ্যাকসিন ডিসিটিআই করেছি দুটি ডোজ
127.92 - 130.68: লাগবে তিন মাসের অন্তর। আমরা
130.68 - 133.46: স্বাস্থ্য মন্ত্রণালয় থেকে কথাবার্তা শুরু
133.46 - 135.48: করবো। ডেঙ্গির ভ্যাকসিন নিয়ে আলোচনা
135.48 - 136.70: হবে। কিন্তু এটা জানুয়ারি ফেব্রুয়ারি
136.70 - 138.30: মাসের আগে পাবেন না আপনারা।
138.30 - 139.48: তো সেই সময় আমরা করবো।
139.48 - 142.06: এই ডেঙ্গির সিসিমটা আমরা পুরোনোভাবেই
142.06 - 144.08: পালন করতে হবে। চলতি বছর
144.08 - 146.14: তিরিশ এপ্রিল পর্যন্ত এরাজ্যে ডেঙ্গি
146.14 - 148.30: আক্রান্ত হয়েছেন সাতশো সত্তর জন।
148.43 - 150.41: বর্ষার মৌসুমে ডেঙ্গি ও অন্যান্য
150.41 - 152.31: ভেট্টার বাহিত রোগীর সংক্রমণ রুখতে
152.31 - 154.55: তৎপর প্রশাসন। মঙ্গলবার স্বাস্থ্য সচিব
154.55 - 156.75: স্বাস্থ্য শিক্ষা অধিকর্তা সহ সংশ্লিষ্ট
156.75 - 158.91: দফাগুলির সঙ্গে বৈঠকে বসেন স্বাস্থ্য
158.91 - 160.69: মন্ত্রী। সন্দ্বীপ সরকার ও ঝিলাম
160.69 - 163.99: করোন ছায়াদিপুব এবিপি আনন্দ কলকাতা।
163.99 - 166.39: এবিপি আনন্দ এগিয়ে থাকে এগিয়ে
166.39 - 166.87: রাখি।

Transcription & Chunking took 4.10 seconds
Total chunks generated: 75


Transcribing Terrorist(Long) with Faster-whisper-tugstugi...
Streaming Chunked Output:
15.40 - 17.78: নমস্কার দেখছেন জি চব্বিশ ঘন্টা
17.78 - 19.14: আর স্পেশাল চব্বিশ নিয়া আপনাদের
19.14 - 23.38: সঙ্গে রয়েছি আমি সৈকত। জঙ্গি
23.38 - 27.14: এই নামটা শুনলেই প্রথম পাকিস্তানের
27.14 - 30.10: কথা মাথায় আসে। হ্যাঁ পাকিস্তান
30.10 - 32.90: ছাড়া গোটা বিশ্বে জঙ্গি বা
32.90 - 35.18: জঙ্গি দেশ বলতে আর কেউ
35.18 - 38.56: নেই। পাকিস্তান হচ্ছে জঙ্গিদের আঁতুর
38.56 - 40.10: ঘর। আমরা জানি যে এই
40.10 - 43.48: ভারতকে বারবার রক্তাক্ত করেছে পাকিস্তান।
43.48 - 47.06: সেই পাকিস্তান মূলত কাশ্মীর এবং
47.06 - 49.62: কাশ্মীর সংলগ্ন যে রাজ্যগুলি রয়েছে।
49.62 - 51.76: বিশেষ করে উত্তর ভারত এবং
51.76 - 54.53: কিছুটা উত্তর পূর্ব ভারতকে অশান্ত
54.53 - 56.49: করার চেষ্টা করে রক্ত ঝরায়।
56.49 - 61.11: কিন্তু সেই পাকিস্তানি জঙ্গি তারা
61.11 - 63.93: কি এবার বাংলাকেও টার্গেট করছে?
64.89 - 67.41: বাংলাতে ঘাঁটি গেড়ে বসে থাকছে?
67.77 - 70.50: শুধু তাই নয় এ রাজ্যের
70.50 - 73.88: মুখ্যমন্ত্রী শুভেন্দু অধিকারীকেও হত্যার পরিকল্পনা
73.88 - 76.84: করছে। ভাবছেন এত বড় কথা
76.84 - 79.16: বলছি হ্যাঁ বলছি কারণ সেই
79.16 - 81.94: তথ্যই তো পেয়েছে পুলিশ। বেঙ্গল
81.94 - 84.76: এসটিএফের নজরে এই মুহূর্তে হামিম
84.76 - 87.97: মণ্ডল। বাংলায় ঘাঁটি গেড়ে থাকা
87.97 - 91.19: এই জঙ্গির একাধিক তথ্য এখন
91.19 - 94.29: গোয়েন্দাদের হাতে, পুলিশের হাতে কী
94.29 - 95.37: তথ্য উঠে আসছে?
95.85 - 97.85: সবচেয়ে বড় অভিযোগ কী জানেন?
97.97 - 100.47: এই হামিম মণ্ডল আম জনতার
100.47 - 102.29: মতো মিশে থাকতো সাধারণ মানুষের
102.29 - 105.01: সঙ্গে তার নেটওয়ার্ক পাকিস্তান পর্যন্ত।
108.04 - 109.92: আর এই মুহূর্তে আপনাদেরকে একটু
109.92 - 111.78: দেখানোর চেষ্টা করবো যেখান থেকে
111.78 - 114.20: গ্রেফতার করা হয় রেনেসা টাউনশিপ
114.20 - 117.90: সেই রেনেসা টাউনশিপের ঠিক ম্যাপটা
117.90 - 119.26: যদি বোঝানোর চেষ্টা করি ক্যানো
119.26 - 121.12: ম্যাপটা বোঝানোর চেষ্টা করছি কারণ
121.12 - 122.92: এই রেনেসা টাউনশিপেই ক্যানো সে
122.92 - 125.13: ঘাঁটি গেড়েছিলো কারন যাতে সে
125.13 - 127.05: পালাতে পারে। যাতে সেখান থেকে
127.05 - 129.03: সে নেটওয়ার্ক পরিচালনা করতে পারে।
129.03 - 132.19: দেখুন ভালো করে। স্কুল, পাশেই
132.19 - 135.11: দুটো স্কুল রয়েছে। যাতে বড়
135.11 - 137.01: নাশকতা ঘটালে এই স্কুলকে বেছে
137.01 - 138.82: নেওয়া যেতে পারে। শপিং মল
138.82 - 140.72: অর্থাৎ বড়ো নাশকতা বেশি মানুষ
140.72 - 142.26: জমায়েত থাকবে সেজন্য শপিং মল
142.26 - 144.92: পাশে এবং জাতীয় সড়কের দূরত্ব
144.92 - 147.22: বেশি নয় মেরে কেটে মাত্র
147.22 - 148.94: কয়েকশো মিটার বলা যেতে পারে
148.94 - 151.14: এখানেও জাতীয় সড়ক রয়েছে পাশেই
151.14 - 153.48: রয়েছে ক্যান্সার হাসপাতাল এবং সবচেয়ে
153.48 - 154.38: বড় কথা কী জানেন?
154.86 - 158.02: সবচেয়ে বড় কথা বর্ধমানের খাগড়াগড়,
158.30 - 160.74: যে খাগড়াগড় বিস্ফোরণের পর এনায়
160.74 - 162.64: তদন্তে উঠে এসেছিল জঙ্গি মডিউল,
162.78 - 165.42: যেই জঙ্গি মডিউল, সেই খাগড়াগড়ো
165.42 - 166.96: এখান থেকে মেরে কেটে মাত্র
166.96 - 169.32: কয়েক কিলোমিটার দূর। ফলে সব
169.32 - 171.28: মিলে যেটা বোঝা যাচ্ছে এই
171.28 - 173.97: জঙ্গি জাল তার পেছনে কি
173.97 - 177.19: বড় কোনো নাশকতার পরিকল্পনা ছিলো?
177.33 - 180.23: আর এইজন্য মানুষের সঙ্গে মিশে
180.23 - 182.37: থাকতো এই জঙ্গিরা।
190.18 - 192.56: মনে করুন আপনি জিমে শরীরচর্চা
192.56 - 195.88: করছেন কিংবা সবজির বাজারে সবজির
195.88 - 198.18: দরদাম করছেন। ঘুনাক্ষরেও টেন পারছেন
198.18 - 199.68: না আপনার পাশেই দাঁড়ি আছে
199.68 - 202.58: কোনো খুনি সন্ত্রাসবাদী জঙ্গি। পাক
202.58 - 205.36: মদতপুষ্ট জঙ্গি হামিমকে দেখে তেমনি
205.36 - 207.44: বোঝার উপায় ছিলো না। সে
207.44 - 209.30: আই এস আই নিযুক্ত নৃশংস
209.30 - 212.44: জঙ্গি সংগঠন জেইসের সদস্য। পরিচয়
212.44 - 214.02: লুকোতে। কখনো সে দর্জির কাজ
214.02 - 216.22: করতো বর্ধমান থেকে হাওড়া রুটে
216.22 - 218.92: ছিল অবাধ বিচরণ। হাওড়ার কোথায়
218.92 - 220.92: কোথায় সে জঙ্গি নেটওয়ার্ক তৈরি
220.92 - 222.80: করেছিলো খতিয়ে দেখছে পুলিশ। কিন্তু
222.80 - 224.62: কিভাবে পুলিশের নজরে এলো এই
224.62 - 225.24: জঙ্গি হামিম?
229.51 - 235.57: বর্ধমান শহর থেকে হাওড়ার পিলখানা।
235.57 - 238.35: বাংলায় ক্ষমতায় এসেই অনুপ্রবেশকারী আটকাতে
238.35 - 240.23: সীমান্তে বেড়া দিতে জমি দিয়েছেন
240.23 - 242.91: বিএসএফে। শুভেন্দু অধিকারীর রাজত্বে পুলিশ
242.91 - 244.73: এখন তীক্ষ্ণ দৃষ্টি দিচ্ছে রাজ্যের
244.73 - 246.89: সুরক্ষায়। ঠিক সেসময় এমন এক
246.89 - 249.39: খবরে বাংলায় রীতিমতো শিখরোন। বাংলায়
249.39 - 251.19: ঘাটি গেড়েছিলো যে শিম মোহাম্মদ
251.19 - 253.41: জঙ্গে। তাও আবার শহরের উপকণ্ঠে
259.37 - 261.79: কোনও ঘিঞ্জি শহর বা এলাকায়
261.79 - 264.57: কোনও অপারেশনের আগে জঙ্গিরা সাধারণত
264.57 - 266.59: মানুষের মধ্যে মিশে থাকে। এটা
266.59 - 269.17: জঙ্গিদের চিরাচরিত প্যাটার্ন। বাংলাতেও তার
269.17 - 271.39: অন্যথা হয়নি। বাংলার অন্যতম শহর
271.39 - 273.63: হাওড়া। অত্যন্ত ঘিঞ্জি আর পুরনো
273.63 - 276.05: শহরকেই টার্গেট করেছিলো পাকিস্তানি জঙ্গি।
276.05 - 278.75: নাম হামিম মন্ডল। হাওড়ার পিলখানা
278.75 - 280.97: অত্যন্ত জনবহুল একটি এলাকা। এই
280.97 - 283.81: অঞ্চলে বেশি সংখ্যালঘুদেরই বসবাস। সেখানে
283.81 - 285.69: একটি গেঞ্জি কারখানায় কাজ করতো
285.69 - 288.21: জঙ্গি হামিম। এই পিলখানায় বসেই
288.21 - 289.77: কড়া নজর রাখতো শহরের নামী
289.77 - 292.29: দামী রাজনৈতিক ব্যক্তিদের ওপর। সম্প্রতি
292.29 - 294.07: পিলখানার কিছু এলাকায় উচ্ছেদ অভিযান
294.07 - 295.87: শুরু হয়। উচ্ছেদ অভিযানের সময়
295.87 - 297.91: হামিম বর্ধমানে চলে যায়। এমনটাই
297.91 - 306.80: পুলিশ সূত
308.10 - 310.22: তখন সদ্য মন্ত্রী হয়েছেন উত্তর
310.22 - 312.08: হাওড়ার বিজেপি বিধায়ক উমেশ রাই।
312.08 - 313.92: প্রতিদিন প্রচুর ফোন আসছে। তার
313.92 - 315.12: মধ্যি একটি ফোন কল পেয়ে
315.12 - 317.22: পুলিশের দ্বারস্থ হয়েছিলেন মন্ত্রী উমেশ।
317.22 - 319.62: অভিযোগ। পাকিস্তানি এজেন্সির কথা বলে
319.62 - 321.30: মোটা টাকা দাবি করা হয়।
321.30 - 323.20: মন্ত্রীর পুত্রকে অপহরণ করার হুমকি
323.20 - 325.18: দেয় হামিম। বিজেপি অফিসের ছবি
325.18 - 327.63: পাঠিয়ে হামলার হুমকিও দেওয় আমাকে
327.63 - 330.43: পাকিস্তানি একটা এজেন্সি থেকে অনেকবার
330.43 - 331.99: আমাকে থ্রেড করেছে। আমার ছেলেকে
331.99 - 333.81: কিডন্যাপ করার থ্রেড করেছিলো। আমি
333.81 - 335.25: কোনোদিন সাম্বাদ মাধ্যমে এই বিষয়ে
335.25 - 338.79: বলিনি। পুলিশকে জানিয়েছিলাম। পুলিশ ব্যবস্থা
338.79 - 340.72: করছিলো। আমার মনে হচ্ছে তারই
340.72 - 342.30: পরিমাণ মেটায়। ফোন করে হুমকি
342.30 - 344.18: দেওয়া হচ্ছিলো। এবং তার কাছে
344.18 - 346.34: আন্তর্জাতিক থ্রেড কল আসছিলো। পাকিস্তানি
346.34 - 347.98: এজেন্সি থেকে ফোন করা হচ্ছিলো।
347.98 - 349.52: এবং তাকে তার ওপর হামলা
349.52 - 350.94: চালালো, তার পার্টি অফিসে হামলা
350.94 - 354.00: চালালো। এমনকি তার ছেলেকে অপহরণের
354.00 - 355.78: হুমকি পর্যন্ত দেওয়া হয়েছিলো। এই
355.78 - 357.52: ঘটনার পর তিনি হাওড়া সিটি
357.52 - 358.48: পুলিশের উচ্চপদস্থ

,Video,WER %,CER %,Word Accuracy %,GT Words,Pred Words,Correct Words,Substitutions,Deletions (Missed),Insertions
0,Rain,24.65,11.94,75.81,215,203,163,39,13,1
1,Delhi Protest,23.12,7.28,79.03,186,185,147,34,5,4
2,Subhendu CM,32.27,15.63,69.97,626,587,438,135,53,14
3,Dengue,31.59,11.87,70.88,364,367,258,100,6,9
4,Terrorist(Long),31.58,14.04,71.94,2527,2482,1818,575,134,89
5,Taslima Nasrin(Long),30.11,14.27,74.49,2670,2672,1989,560,121,123
6,Shamik(Long),33.94,13.27,70.10,2625,2660,1840,714,71,106
7,10am News(Long),32.74,13.43,69.99,2456,2383,1719,597,140,67

### Faster-whisper-bitwisemind

In [2]:
from faster_whisper import WhisperModel, BatchedInferencePipeline

model = WhisperModel("models\\bitwisemind_sam_ct2_float16", device="cuda", compute_type="float16")

batched_model = BatchedInferencePipeline(model=model)

print("Loaded batched model successfully")

Loaded batched model successfully

In [4]:
run_transcription(
    batched_model=batched_model,
    model_name="Faster-whisper-bitwisemind",
    language='bn',
    vad_parameters={"min_silence_duration_ms": 4000, "speech_pad_ms": 5000}
)

Transcribing Rain with Faster-whisper-bitwisemind...
Streaming Chunked Output:
0.00 - 2.20: দক্ষিণবঙ্গে আজ ও কাল ভারী
2.20 - 4.58: বৃষ্টির সম্ভাবনা কলকাতায় দফায় দফায়
4.58 - 6.86: বৃষ্টির সম্ভাবনা থাকছে শুক্রবার থেকে
6.86 - 9.14: এই বৃষ্টি কমবে কলকাতায় দুই
9.14 - 10.90: চব্বিশ পরগনায় ভারী বৃষ্টির হলুদ
10.90 - 12.66: সতর্কতা রয়েছে ভারী বৃষ্টির সতর্কতা
12.66 - 15.42: থাকছে পূর্ব মেদিনীপুর পশ্চিম বর্ধমান
15.42 - 19.22: বাঁকুড়াতেও অন্য জেলাতেও বিক্ষিপ্ত দুই
19.22 - 21.70: এক পশলা বৃষ্টির সম্ভাবনা থাকছে
21.70 - 24.68: শনি এবং রবিবার দক্ষিণবঙ্গে বৃষ্টির
24.68 - 29.14: পরিমাণ কমবে আর অন্যদিকে উত্তরবঙ্গে
29.14 - 34.78: আগামীকাল থেকে বৃষ্টির পরিমাণ কমবে
34.78 - 36.30: অয়ন ঘোষাল আমাদের প্রতিনিধি রয়েছেন
36.30 - 37.54: আমাদের সঙ্গে অয়ন সব মিলিয়ে
37.54 - 39.18: কি পূর্বাভাস হাওয়া অফিসে
43.89 - 46.81: এই মুহূর্তে মৌসুমী অক্ষরেখা মুর্শিদাবাদ
46.81 - 49.37: থেকে গাঙ্গেয় দক্ষিণবঙ্গের প্রায় ওপর
49.37 - 51.53: দিয়ে বাংলাদেশ পর্যন্ত বিস্তৃত সেই
51.53 - 53.49: মৌসুমে অক্ষরেখার হাত ধরে যে
53.49 - 55.09: বৃষ্টি গতকাল থেকে শুরু হয়েছে
55.09 - 56.79: সেই বৃষ্টি আজ বুধবার এবং
56.79 - 59.85: আগামীকাল বৃহস্পতিবার পর্যন্ত গোটা দক্ষিণবঙ্গেই
59.85 - 62.19: তার দাপট দেখাবে বৃষ্টির সঙ্গে
62.43 - 64.15: ত্রিশ থেকে চল্লিশ কিলোমিটার বেগে
64.15 - 66.49: দমকা ঝোড়ো হাওয়ার পূর্বাভাস রয়েছে
66.49 - 68.49: উপকূলের জেলার ক্ষেত্রে এই দমকা
68.49 - 70.23: ঝোড়ো হাওয়ার গতিবেগ কোন কোন
70.23 - 72.27: জায়গায় পঞ্চাশ কিলোমিটার পর্যন্ত হতে
72.27 - 75.11: পারে উপকূল এলাকাতে বৃষ্টিপাতের পরিমাণ
75.11 - 77.11: গাঙ্গেয় দক্ষিণবঙ্গের থেকে বেশি থাকবে
77.40 - 79.80: এই অবস্থা বৃহস্পতিবার পর্যন্ত চলার
79.80 - 81.90: পর শুক্র শনি এবং রবি
81.90 - 84.22: উত্তর এবং দক্ষিণবঙ্গে লক্ষণীয় ভাবে
84.22 - 87.62: বৃষ্টিপাতের পরিমাণ কমবে উত্তরবঙ্গে বৃহস্পতিবারের
87.62 - 89.88: পর এবং দক্ষিণবঙ্গে শুক্রবারের পর
89.88 - 91.76: থেকে কমে যাওয়া বৃষ্টি নতুন
91.76 - 93.74: করে উত্তরবঙ্গে মঙ্গলবারের পর থেকে
93.74 - 96.26: বৃষ্টি বাড়ার সম্ভাবনা দক্ষিণবঙ্গের ক্ষেত্রে
96.26 - 98.36: আগামী বুথ বা বৃহস্পতিবার থেকে
98.36 - 99.32: ঝড় এবং বৃষ্ট
108.17 - 112.63: বাংলার আওয়াজ বাঙালির আবেগ চব্বিশ
112.63 - 113.05: ঘন্টা

Transcription & Chunking took 3.09 seconds
Total chunks generated: 42


Transcribing Delhi Protest with Faster-whisper-bitwisemind...
Streaming Chunked Output:
6.54 - 9.16: ছাত্রদের আন্দোলনে উত্তপ্ত হয়ে উঠেছে
9.16 - 12.50: ভারতের রাজধানী নয়াদিল্লি নয়াদিল্লিতে মেডিকেল
12.50 - 14.52: ভর্তি পরীক্ষা সংক্রান্ত প্রশ্ন ফাঁস
14.52 - 20.08: ও গতকাল সোমবার বিশ জুলাই
20.08 - 23.36: সংসদের বর্ষাকালীন অধিবেশন চলাকালে ককরোজ
23.36 - 26.00: জনতা পার্টির ব্যানারে হাজারো আন্দোলনকারী
26.00 - 28.42: নিরাপত্তা ব্যারিকেড ভেঙে সংসদ ভবনের
28.42 - 30.44: মূল ফটকের দিকে অগ্রসর হন
30.44 - 37.84: এসময় ভবনের ভেতরেই প্রধানমন্ত্রী উপস্থিত
37.84 - 40.64: ছিলেন পরিস্থিতি ক্রমশ উত্তপ্ত হয়ে
40.64 - 43.16: উঠলে ও বিক্ষোভকারীদের সাথে পুলিশের
43.16 - 45.14: দফায় দফায় সংঘর্ষ শুরু হলে
48.97 - 52.03: শিক্ষার্থীদের আন্দোলনে পুলিশের ব্যাপক লাঠিচার্জ
52.03 - 54.41: এবং রাবার বুলেট নিক্ষেপের পর
54.41 - 55.61: এই আন্দোলন এখন
65.37 - 67.57: মে মাসে যাত্রা শুরু করার
67.57 - 69.73: পর থেকে সিজেপি সোশ্যাল মিডিয়ায়
69.73 - 72.11: লক্ষ লক্ষ অনুসারী অর্জন করেছে
72.11 - 74.17: যা দুই হাজার চব্বিশ সালে
74.17 - 76.35: তৃতীয়বারের মত ক্ষমতায় আসার পর
76.35 - 79.75: থেকে হিন্দু জাতীয়তাবাদী প্রধানমন্ত্রী নরেন্দ্র
79.75 - 81.83: মোদীর জন্য অন্যতম বড় চ্যালেঞ্জ
81.83 - 82.69: তৈরি করেছে
84.12 - 86.82: সিজেপির আশুতোষ একটি সোশ্যাল মিডিয়া
86.82 - 89.42: পোস্টে বলেছেন আমরা থামবো না
89.42 - 93.54: প্রধানকে বরখাস্ত করতেই হবে মঙ্গলবারও
93.54 - 95.76: শত শত বিক্ষোভকারী যন্ত্র মন্ত্রের
95.76 - 99.00: প্রতিবাদিস্থলে অবস্থান করছেন যাদের অনেকেই
99.00 - 102.12: শিক্ষাব্যবস্থায় ব্যাপক পরিবর্তনের আহ্বান জানাচ্ছিলেন
108.70 - 110.94: সোমবার প্রায় পাঁচ বছরের মধ্যে
110.94 - 112.90: দিল্লির অন্যতম বৃহত্তম এক গণ
112.90 - 115.86: সমাবেশে বিক্ষোভকারীদের সংসদ অভিমুখে মিছিল
115.86 - 117.66: করতে বাধা দিতে পুলিশ কাঁদানে
117.66 - 119.60: গ্যাস ও লাঠিচার্জ করে বলে
119.60 - 122.96: জানা গেছে বিক্ষোবের আয়োজকরা কর্তৃপক্ষের
122.96 - 125.02: এই একনায়ক সুলভ আচরণের নিন্দা
125.02 - 127.70: করেছেন এবং বলেছেন যে শত
127.70 - 130.04: শত বিক্ষোভকারী আহত হয়েছেন

Transcription & Chunking took 2.73 seconds
Total chunks generated: 38


Transcribing Subhendu CM with Faster-whisper-bitwisemind...
Streaming Chunked Output:
0.00 - 3.52: মমতা বন্দোপাধ্যায় যে হেরে গিয়েছেন
3.52 - 5.14: সেটাই কার্য তো মেনে নিচ্ছিলেন
5.14 - 6.94: না মমতা বন্দোপাধ্যায় কিন্তু না
6.94 - 10.28: অবশেষে শুভেন্দু অধিকারীকে মুখ্যমন্ত্রী হিসেবে
10.28 - 12.76: মেনে নিলেন মমতা বন্দোপাধ্যায় গতকাল
12.76 - 14.68: ফেসবুক লাইভ করলেন সেখানে অনেক
14.68 - 16.22: কিছু বললেন আর তার মধ্যেই
16.22 - 19.50: দেখা গেল অবশেষে শুভেন্দু অধিকারীকে
19.50 - 23.17: মুখ্যমন্ত্রী মানলেন মমতা মমতা বন্দোপাধ্যায়
23.17 - 27.19: যিনি আজকে মুখ্যমন্ত্রী হয়েছেন আমার
27.19 - 28.65: অনেক শুভেচ্ছা থাকবে কিন্তু এটা
28.65 - 29.89: আমি নিশ্চয়ই বলবো না যে
29.89 - 31.99: আপনি মুখ্যমন্ত্রী হয়েছেন বলে আপনি
31.99 - 34.67: তৃণমূলটা করেননি আপনিও কংগ্রেস করতেন
34.67 - 37.13: একদিন আপনিও নির্বাচনে অনেকবার হেরেছেন
37.13 - 38.39: এবং আপনার জন্য আমি বারবার
38.39 - 40.58: যেতাম আপনার কেন্দ্রে সেটা আমার
40.58 - 42.26: কর্তব্য ছিল এর জন্য আমি
42.26 - 46.92: কোন কৃতিত্ব নিচ্ছি না আবির
46.92 - 48.28: রয়েছে আমার সঙ্গে আবিরের কাছ
48.28 - 50.66: থেকে জানতে চাইব আবির অবশেষে
50.66 - 52.50: শুভেন্দুকে মানলেন মমতা
56.00 - 58.12: দেখো চৌঠা মেয়ের ফল প্রকাশের
58.12 - 60.68: পর মমতা বন্দোপাধ্যায় তিনি রাজভবনেও
60.68 - 63.16: যাননি ইস্তফা দিতে এমনকি তারপরে
63.16 - 65.00: তিনি যে সাংবাদিক সম্মেলন কালিঘাটের
65.00 - 67.08: বাড়িতে ডেকেছিলেন সেখানে দাঁড়িয়েও তিনি
67.08 - 68.96: উল্লেখ করেছিলেন বা তিনি যে
68.96 - 70.66: হেরে গেছেন সেটাকে কার্যত স্বীকার
70.66 - 72.54: করেননি হারিয়ে দেওয়া হয়েছে এমন
72.54 - 74.68: একটা অভিযোগ তিনি করেছিলেন এবং
74.68 - 76.14: প্রায় দ্বিদীর্ঘ সময় ধরে তিনি
76.14 - 77.86: তার নিজের বক্তব্যের জায়গাতে অনর
77.86 - 80.34: ছিলেন একাধিক যারা তৃণমূল কংগ্রেসের
80.34 - 82.16: নেতারা তারা প্রকাশ্যে প্রথম দিকে
82.16 - 83.80: বলতে না পারলেও পরবর্তী সময়
83.80 - 85.48: তারাও বলতে শুরু করেন যে
85.48 - 88.70: ভূমিকা পালন করা হচ্ছে তা
88.70 - 90.76: যথাযথই নয় হারটাকে সহজ করে
90.76 - 92.74: স্বীকার করে নেওয়া উচিত এবং
92.74 - 94.98: পরবর্তী সময়ে তৃণমূল কংগ্রেস ভেঙেও
94.98 - 98.78: যায় এবং ভেঙ
104.36 - 106.04: এর মধ্যে আজকে দেখতে পাওয়া
106.04 - 107.86: গেল যে সোশ্যাল মিডিয়াতে তিনি
107.86 - 109.36: তার পেজে যে লাইভ করেছেন
109.36 - 110.82: সে লাইভ এর মধ্যে তিনি
110.82 - 114.28: কার্যত মুখ্যমন্ত্রী শুভেন্দু অধিকারীকে কার্যত
114.28 - 116.38: তিনি মেনে নিয়েছেন এবং তার
116.38 - 118.28: কাজের যে বিষয় সেই বিষয়ের
118.28 - 120.02: কথাও তিনি মনে করিয়ে রেখেছেন
120.02 - 121.12: আসলে যে দু মাস পরে
121.12 - 122.22: তার মেনে নেওয়ার যে বিষয়
122.22 - 123.34: তাতে মনে করা হচ্ছে যে
123.34 - 125.67: এক তৃণমূল কংগ্রেসের ভাঙ্গন প্রায়
125.67 - 127.75: প্রত্যেকদিনই হয়ে চলেছে এবং এমন
127.75 - 128.85: একটা সময় দাঁড়িয়ে তাকে এই
128.85 - 130.53: কথাগুলো বলতে হচ্ছে যখন তৃণমূল
130.53 - 132.63: কংগ্রেস বলতে যে সমস্ত নেতারা
132.63 - 134.91: পরিচিত ছিলেন মমতা বন্দোপাধ্যায়ের পরে
134.91 - 136.51: তারা ভেঙে বেরিয়ে চলে গিয়েছেন
136.51 - 138.01: এবং তারাও দুষছেন হচ্ছে তৃণমূল
138.01 - 140.45: কংগ্রেসের কালীঘাট পন্থী যে কৌশল
140.45 - 142.84: রাজনৈতিক কৌশল তাকে দাঁড� এবং
142.84 - 144.88: মমতা বন্দোপাধ্যায় হয়তো বুঝতে পেরেছেন
144.88 - 147.72: যে বাস্তবের এবং যে কল্পনার
147.72 - 149.04: যে মিশেল তার দুটোর মধ্যে
149.04 - 151.12: ফারাক কোথায় রয়েছে এবং বর্তমান
151.12 - 152.88: দিনে দাঁড়িয়ে বাস্তবের মাটিতে দাঁড়িয়ে
152.88 - 154.72: যে পরিস্থিতি শিকার তৃণমূল কংগ্রেসের
154.72 - 156.78: কালিঘাট পন্থী নেতাদেরকে হতে হচ্ছে
156.78 - 158.68: তাতে এখনো পর্যন্ত যদি হার
158.68 - 159.94: স্বীকার না করা এবং নতুন
159.94 - 162.52: মুখ্যমন্
166.06 - 167.78: এটা কি যে তৃণমূল কংগ্রেসের
167.78 - 169.70: যে সমস্ত নেতারা বিশেষত সাংসদরা
169.70 - 171.68: এনসিপিএতে যোগ দিয়েছেন যে সমস্ত
171.68 - 174.02: বিধায়করা আলাদা ব্লক তৈরি করেছেন
174.02 - 176.30: তারা প্রত্যেকেই কখনো না কখনো
176.30 - 178.08: গত কয়েকদিনের কথাবার্তার মধ্যে বুঝিয়ে
178.08 - 180.02: দেবার চেষ্টা করেছেন যে বক্তব্য
180.02 - 181.50: রাখা হয়েছিল হার স্বীকার না
181.50 - 183.32: করার প্রসঙ্গে দাঁড়িয়ে তা ঠিক
183.32 - 186.71: নয় এমনকি রাজ্য বিধা দাঁড়িয়ে
186.71 - 188.21: বিরোধী দল নেতাকে ওই প্রসঙ্গ
188.21 - 189.95: নিয়ে কটাক্ষ কমতে শোনা গিয়েছিল
189.95 - 192.21: এবং মুখ্যমন্ত্রীকেও নানাভাবে কটাক্ষ করতে
192.21 - 193.57: দেখতে পাওয়া যায় এবং দুই
193.57 - 194.61: হাজার একুশ এবং দুই হাজার
194.61 - 198.35: ছাব্বিশ দুটোতেই মমতা বন্দোপাধ্যায় শুভেন্দু
198.35 - 200.17: অধিকারীর কাছে তিনি পরাস্ত হয়েছেন
200.17 - 201.47: এবং যে শুভেন্দু অধিকারী একটা
201.47 - 202.65: সময় তৃণমূল কংগ্রেসে ছ
204.40 - 206.20: তার রেশ টানতে গিয়ে আজকে
206.20 - 208.00: যেটা বলেছেন তাতে এটা পরিষ্কার
208.00 - 209.96: যে বক্তব্য তিনি রেখেছিলেন বাস্তবের
209.96 - 211.86: মাটিতে দাঁড়িয়ে আজকে সেই বক্তব্যের
211.86 - 213.56: প্রেক্ষিতে দাঁড়িয়ে কোন ব্যক্তি বিশ্বাস
213.56 - 214.84: করতে চাইবেন না বা এই
214.84 - 216.40: বাস্তবের মাটিতে দাঁড়িয়ে এই রাজনীতিকে
216.40 - 217.72: এগিয়ে নিয়ে যাওয়াটা সম্ভব নয়
217.72 - 219.42: সেই কারণেই আজকে তিনি কার্যত
219.42 - 219.76: স্ব
223.18 - 224.48: মানে বাড়তে শুরু করেছে তাতে
224.48 - 226.50: অনেকেই বলছেন এটাই কাম্য ছিল
226.50 - 228.26: তবে দুমাস পরে কেন তিনি
228.26 - 229.78: করলেন তাতে অনেকটা সময় নষ্ট
229.78 - 231.38: হয়েছে এবং তৃণমূল কংগ্রেসের যে
231.38 - 233.72: ভাবমূর্তি ক্ষুন্ন হয়েছে এটাই অনেকেই
233.72 - 234.94: এই মুহূর্তে বলতে শুরু করেছেন
234.94 - 238.90: যিনি আজকে মুখ্যমন্ত্রী হয়েছেন আমার
238.90 - 240.34: অনেক শুভেচ্ছা থাকবে কিন্তু এটা
240.34 - 241.83: আমি নিশ্চয়ই বলবো না আপনি
241.83 - 244.19: মুখ্যমন্ত্রী হয়েছেন বলে আপনি তৃণমূলটা
244.19 - 247.01: করেননি আপনিও কংগ্রেস করতেন একদিন
247.01 - 249.01: আপনিও নির্বাচনে অনেকবার হেরেছেন এবং
249.01 - 250.63: আপনার জন্য আমি বারবার যেতাম
250.63 - 252.69: আপনার কেন্দ্রে সেটা আমার কর্তব্য
252.69 - 254.21: ছিল এর জন্য আমি কোন
254.21 - 254.99: কৃতিত্ব নিচ্ছি না

Transcription & Chunking took 5.80 seconds
Total chunks generated: 119


Transcribing Dengue with Faster-whisper-bitwisemind...
Streaming Chunked Output:
0.00 - 2.58: ভারতে প্রথমবার আসছে ডেঙ্গি ভ্যাকসিন
2.58 - 5.38: কিউ ডেঙ্গা ভ্যাকসিন বাণিজ্যিকভাবে বিক্রির
5.38 - 7.60: অনুমোদন দিল ড্রাগ কন্ট্রোল জেনারেল
7.60 - 9.30: অফ ইন্ডিয়া তবে এই ভ্যাকসিন
9.30 - 10.92: বাজারে আসতে আরো কয়েক মাস
10.92 - 14.70: সময় লাগবে বলে জানিয়েছেন স্বাস্থ্যমন্ত্রী
14.70 - 16.76: বছর বছর বর্ষা এলে এই
16.76 - 18.80: রাজ্যে বাড়ে ডেঙ্গির প্রকোপ প্রতিবছর
18.80 - 20.78: মশাবাহিত রোগে আক্রান্ত হন হাজার
20.78 - 22.92: হাজার মানুষ সেই লড়াইয়ে এবার
22.92 - 24.74: নতুন হাতিয়া পেল দেশ ভারতে
24.74 - 26.60: প্রথমবার আসতে চলেছে ডেঙ্গির প্রতিষেধক
26.60 - 28.40: ভ্যাকসিন ড্রাগ কন্ট্রোল জেনারেল অফ
28.40 - 31.22: ইন্ডিয়া বাণিজ্যিকভাবে ডেঙ্গির ভ্যাকসিন কিউটেঙ্গা
31.22 - 33.64: ব্যবহারের অনুমোদন দিয়েছে জাপানের তাকে
33.64 - 34.84: তার বায়োফার্মাসিউটিক্যালসে
35.98 - 37.56: চার থেকে সাত বছর বয়সীদের
37.56 - 39.36: দেয়া হবে সহস্র দাবি এই
39.36 - 41.00: ভ্যাকসিন নেয়ার জন্য কোন প্রি
41.00 - 42.72: ভ্যাকসিনেশন স্ক্রিনিং এর প্রয়োজন হবে
42.72 - 44.66: না অর্থাৎ আগে কখনো ডেঙ্গি
44.66 - 46.32: হইছে কিনা তা যাচাই না
46.32 - 48.18: করেও এই টিকা নেওয়া সম্ভব
48.18 - 51.94: এটা ঠিক যে একবার দুবার
51.94 - 54.56: ডেঙ্গু হয়ে গেলে মানুষ ডেঙ্গু
54.56 - 56.55: ইমিউন হয়ে যায় তো সেটা
56.55 - 60.21: যদি আমি আর্টিফিশিয়ালি একটা ইনফেকশনের
60.21 - 62.79: মতন করে দিতে পারি তাহলে
62.79 - 66.05: আমি ভীষণভাবেই আশাবাদী যে ডেঙ্গুটা
66.05 - 68.19: প্রিভেন্ট করা যাবে রিসেন্ট স্টাডিসে
68.19 - 70.65: দেখা গেছে যে এই ডেঙ্গু
70.65 - 73.33: ভ্যাকসিনটা ইজ কোয়েট সেফ এন্ড
73.33 - 76.11: ইফেক্টিভ প্রস্তুতকারী সংস্থার দাবি ডেঙ্গি
76.11 - 78.79: ভাইরাসের চারটি সেরোটাইপের বিরুদ্ধেই সুরক্ষা
78.79 - 80.61: দিতে সক্ষম এই ভ্যাকসিন আমাদের
80.61 - 82.93: কোন আগে টেস্ট করতে হচ্ছে
82.93 - 84.83: না যে প্রেসেন্ট আগে দিয়ে
84.83 - 87.63: ইনফেক্ট ছিল কি ছিল না
87.63 - 90.37: অ্যান্টিবডি আছে কি নেই স্ট্রেট
90.37 - 92.49: ভ্যাকসিনটা দিয়ে দেওয়া যাবে আমরা
92.49 - 94.23: যে নিমোনিয়ার একটা ভ্যাকসিন এখন
94.23 - 96.23: পেয়েছি যে একটা দিলেই লাইফটাইম
96.23 - 98.61: হয়ে যাচ্ছে অনেকটা সেই রকমই
98.61 - 100.97: হলো যে একটা ভ্যাকসিন দিলে
100.97 - 103.43: যদি এখানে আমাদের দুটো ভ্যাকসিন
103.43 - 106.45: দিতে হবে প্রথম ভ্যাকসিন তিন
106.45 - 108.63: মাস পরে আবার সেকেন্ড ভ্যাকসিন
108.63 - 110.73: কিন্তু তাতে আমাদের পুরো খাবার
111.40 - 114.06: ইতিমধ্যেই সুইজারল্যান্ড ইন্দোনেশিয়া মালয়েশিয়া সহ
114.06 - 115.98: তেতাল্লিশ টি দেশে অনুমোদন পেয়েছে
115.98 - 118.50: কিউটেঙ্গা আটটির বেশি দেশে অন্তত
118.50 - 119.94: আঠাশ হাজার মানুষের উপর চালানো
119.94 - 122.80: হয় ক্লিনিকাল ট্রায়াল ভারতে সফলভাবে
122.80 - 125.02: ফেস থ্রি ট্রায়ালও সম্পন্ন হয়েছে
125.02 - 127.64: কিউটেং ভ্যাকসিন ডিসিটিআই করেছি দুটি
127.64 - 129.42: ডোজ লাগবে তিন মাসের অন্তর
129.84 - 133.16: আমরা স্বাস্থ্য মন্ত্রণালয় থেকে কথাবার্তা
133.16 - 135.10: শুরু করব ডেঙ্গির ভ্যাকসিন নিয়ে
135.10 - 136.40: আলোচনা হবে কিন্তু এটা জানুয়ারি
136.40 - 137.72: ফেব্রুয়ারি মাসের আগে পাবেন না
137.72 - 139.16: আপনারা তো সেই সময় আমরা
139.16 - 140.94: করব এই ডেঙ্গি সিজেমটা আমরা
140.94 - 143.80: পুরনোভাবেই পালন করতে হবে চলতি
143.80 - 145.82: বছর ত্রিশশ এপ্রিল পর্যন্ত এরাজ্যে
145.82 - 147.88: ডেঙ্গি আক্রান্ত হয়েছেন সাতশ সত্তর
147.88 - 149.89: জন বর্ষার মৌসুমে ডেঙ্গি ও
149.89 - 151.81: অন্যান্য ভেক্টর বাহিত রোগের সংক্রমণ
151.81 - 154.23: রুখতে তৎপর প্রশাসন মঙ্গলবার স্বাস্থ্য
154.23 - 155.91: সচিব স্বাস্থ্য শিক্ষা অধিকর্তা সহ
155.91 - 158.61: সংশ্লিষ্ট দস্তগুলির সঙ্গে বৈঠকে বসেন
158.61 - 160.81: স্বাস্থ্যমন্ত্রী সন্দীপ সরকার ও ঝিলামকরণ
160.81 - 164.59: জায়দিপুর এবিপি আনন্দ কলকাতা এবিপি
164.59 - 166.79: আনন্দ এগিয়ে থাকে এগিয়ে রাখি

Transcription & Chunking took 4.03 seconds
Total chunks generated: 73


Transcribing Terrorist(Long) with Faster-whisper-bitwisemind...
Streaming Chunked Output:
15.30 - 18.00: নমস্কার দেখছেন চব্বিশ ঘন্টা আর
18.00 - 19.38: স্পেশাল চব্বিশ নিয়ে আপনাদের সঙ্গে
19.38 - 24.26: রয়েছি আমি সৈকত জঙ্গি এই
24.26 - 27.36: নামটা শুনলেই প্রথম পাকিস্তানের কথা
27.36 - 30.60: মাথায় আসে হ্যাঁ পাকিস্তান ছাড়া
30.60 - 33.44: গোটা বিশ্বে জঙ্গি বা জঙ্গি
33.44 - 35.48: দেশ বলতে আর কেউ নেই
35.76 - 38.86: পাকিস্তান হচ্ছে জঙ্গিদের আতুর ঘর
38.86 - 40.58: আমরা জানি যে এই ভারতকে
40.58 - 44.14: বারবার রক্তাক্ত করেছে পাকিস্তান সেই
44.14 - 47.92: পাকিস্তান মূলত কাশ্মীর এবং কাশ্মীর
47.92 - 50.04: সংলগ্ন যে রাজ্যগুলি রয়েছে বিশেষ
50.04 - 52.32: করে উত্তর ভারত এবং কিছুটা
52.57 - 54.87: উত্তর পূর্ব ভারতকে অশান্ত করার
54.87 - 57.55: চেষ্টা করে রক্ত ঝরায় কিন্তু
57.55 - 61.31: সেই পাকিস্তানি জঙ্গি তারা কি
61.31 - 65.77: এবার বাংলাকেও টার্গেট করছে বাংলাতে
65.77 - 68.25: ঘাঁটি গেড়ে বসে থাকছে শুধু
68.25 - 72.70: তাই এরাজ্যের মুখ্যমন্ত্রী শুভেন্দু অধিকারীকেও
72.70 - 76.26: হত্যার পরিকল্পনা করছে ভাবছেন এত
76.26 - 78.48: বড় কথা বলছি হ্যাঁ বলছি
78.48 - 80.06: কারণ সেই তথ্যই তো পেয়েছে
80.06 - 83.46: পুলিশ বেঙ্গল এসটিএফ এর নজরে
83.46 - 86.65: এই মুহূর্তে হামিম মন্ডল বাংলায়
86.65 - 89.49: ঘাঁটি গেড়ে থাকা এই জঙ্গির
89.49 - 92.57: একাধিক তথ্য এখন গোয়েন্দাদের হাতে
92.57 - 94.93: পুলিশের হাতে কি তথ্য উঠে
94.93 - 97.25: আসছে সবচেয়ে বড় অভিযোগ কি
97.25 - 99.79: জানেন এই হামিম মন্ডল আম
99.79 - 101.75: জনতার মত মিশে থাকতো সাধারণ
101.75 - 104.39: মানুষের সঙ্গে তার নেটওয়ার্ক পাকিস্তান
104.39 - 104.93: পর্যন্ত
108.02 - 109.92: আর এই মুহূর্তে আপনাদেরকে একটু
109.92 - 111.66: দেখানোর চেষ্টা করবো যেখান থেকে
111.66 - 114.24: গ্রেপ্তার করা হয় রেনেসা টাউনশিপ
114.24 - 117.90: সেই রেনেসা টাউনশিপের ঠিক ম্যাপটা
117.90 - 119.22: যদি বোঝানোর চেষ্টা করি কেন
119.22 - 121.14: ম্যাপটা বোঝানোর চেষ্টা করছি কারণ
121.14 - 122.90: এই রেনেসা টাউনশিপেই কেন সে
122.90 - 125.13: ঘাটি গেড়েছিল কারণ যাতে সে
125.13 - 127.03: পালাতে পারে যাতে সেখান থেকে
127.03 - 128.95: সে নেটওয়ার্ক পরিচালনা করতে পারে
128.95 - 132.19: দেখুন ভালো করে স্কুল পাশেই
132.19 - 135.13: দুটো স্কুল রয়েছে যাতে বড়
135.13 - 136.97: নাশকতা ঘটালে এই স্কুলকে বেছে
136.97 - 138.86: নেওয়া যেতে পারে শপিং মল
138.86 - 140.72: অর্থাৎ বড় নাশকতা বেশি মানুষ
140.72 - 142.26: জমায়ত থাকবে সেজন্য শপিং মল
142.26 - 144.90: পাশে এবং জাতীয় সড়কের দূরত্ব
144.90 - 147.20: বেশি নয় মেরে কেটে মাত্র
147.20 - 149.00: কয়েকশো মিটার বলা যেতে পারে
149.00 - 151.16: এখানেও জাতীয় সড়ক রয়েছে পাশেই
151.16 - 153.46: রয়েছে ক্যান্সার হাসপাতাল এবং সবচেয়ে
153.46 - 155.72: বড় কথা কি জানেন সবচেয়ে
155.72 - 158.48: বড় কথা বর্ধমানের খাগড়াগড় যে
158.48 - 161.14: খাগড়াগড় বিস্ফোরণের পর এনায় তদন্তে
161.14 - 163.08: উঠে এসেছিল জঙ্গি মডিউল জেশ
163.08 - 165.70: জঙ্গি মডিউল সেই খাগড়াগড় এখান
165.70 - 167.22: থেকে মেরে কেটে মাত্র কয়েক
167.22 - 169.62: কিলোমিটার দূর ফলে সব মিলে
169.62 - 171.88: যেটা বোঝা যাচ্ছে এই জঙ্গি
171.88 - 174.57: জাল তার পেছনে কি বড়
174.57 - 177.53: কোন নাশকতার পরিকল্পনা ছিল আর
177.53 - 181.03: এইজন্য মানুষের সঙ্গে মিশে থাকতো
181.03 - 183.05: এই জঙ্গিরা
190.18 - 192.28: মনে করুন আপনি জিমের শরীর
192.28 - 194.98: চর্চা করছেন কিংবা সবজির বাজারে
194.98 - 197.76: সবজির দরদাম করছেন ঘুনাক্ষরেও টেন
197.76 - 199.42: পারছেন না আপনার পাশেই দাঁড়িয়ে
199.42 - 202.02: আছে কোন খুনি সন্ত্রাসবাদী জঙ্গি
202.02 - 206.62: পাক তেমনি বোঝার উপায় ছিল
206.62 - 209.32: না সে আইএসআই নিযুক্ত নৃশংস
209.32 - 212.42: জঙ্গি সংগঠন জেশের সদস্য পরিচয়
212.42 - 214.02: লুকোতে কখনো সে দর্জির কাজ
214.02 - 216.22: করত বর্ধমান থেকে হাওড়া রুটে
216.22 - 218.96: ছিল অবাধ বিচরণ হাওড়ার কোথায়
218.96 - 220.92: কোথায় সে জঙ্গি নেটওয়ার্ক তৈরি
220.92 - 222.80: করেছিল খতিয়ে দেখছে পুলিশ কিন্তু
222.80 - 224.64: কিভাবে পুলিশের নজরে এলো এই
224.64 - 225.24: জঙ্গি হামিম
229.45 - 232.23: বর্ধমান শহর থেকে হাওড়ার পিলখানা
232.23 - 238.39: বাংলায় ক্ষমতায় এসেই অনুপ্রবেশকারী আটকাতে
238.39 - 240.27: সীমান্তে বেড়া দিতে জমি দিয়েছেন
240.27 - 242.91: বিএসএফে শুভেন্দু অধিকারীর রাজত্বে পুলিশ
242.91 - 244.71: এখন তীঘ্ন দৃষ্টি দিচ্ছে রাজ্যের
244.71 - 246.69: সুরক্ষায় ঠিক সে সময় এমন
246.69 - 248.57: এক খবরে বাংলায় রীতিমত শিহরণ
248.57 - 251.19: বাংলায় ঘাটি গেড়েছিল জয়েশীম মাহম্মদ
251.19 - 253.43: জঙ্গে তাও আবার শহরের উপকণ্ঠে
259.35 - 261.79: কোন ঘিঞ্জি শহর বা এলাকায়
261.79 - 264.57: কোন অপারেশনের আগে জঙ্গিরা সাধারণত
264.57 - 266.59: মানুষের মধ্যে মিশে থাকে এটা
266.59 - 269.17: জঙ্গিদের চিরাচরিত প্যাটার্ন বাংলাতেও তার
269.17 - 271.45: অন্যথা হয়নি বাংলার অন্যতম শহর
271.45 - 273.61: হাওড়া অত্যন্ত ঘিঞ্জি আর পুরনো
273.61 - 275.87: শহরকেই টার্গেট করেছিল পাকিস্তানি জঙ্গি
275.87 - 278.77: নাম হামিম মন্ডল হাওড়ার পিলখানা
278.77 - 280.95: অত্যন্ত জনবহুল একটি এলাকা এই
280.95 - 283.97: অঞ্চলে বেশি সংখ্যালঘুদেরই বসবাস সেখানেই
283.97 - 285.69: একটি গেঞ্জি কারখানায় কাজ করতো
285.69 - 288.21: জঙ্গি হামিম এই পিলখানায় বসেই
288.21 - 289.77: করা নজর রাখতো শহরের নামই
289.77 - 292.29: দামি রাজনৈতিক ব্যক্তিদের ওপর সম্প্রতি
292.29 - 294.07: পিলখানার কিছু এলাকায় উচ্ছেদ অভিযান
294.07 - 295.87: শুরু হয় উচ্ছেদ অভিযানের সময়
295.87 - 297.91: হামিম বর্ধমানে চলে যায় এমনটাই
297.91 - 298.79: পুলিশ সূত্রে খবর
308.10 - 310.20: তখন সদ্য মন্ত্রী হয়েছেন উত্তর
310.20 - 312.04: হাওড়ার বিজেপি বিধায়ক উমেশ রাই
312.04 - 313.92: প্রতিদিন প্রচুর ফোন আসছে তার
313.92 - 315.14: মধ্যে একটি ফোন কল পেয়ে
315.14 - 317.16: পুলিশের দ্বারস্থ হয়েছিলেন মন্ত্রী উমেশ
317.16 - 319.62: অভিযোগ পাকিস্তানি এজেন্সির কথা বলে
319.62 - 321.06: মোটা টাকা দাবি করা হয়
321.06 - 323.18: মন্ত্রীর পুত্রকে অপহরণ করার হুমকি
323.18 - 325.18: দেয় হামিম বিজেপি অফিসের ছবি
325.18 - 327.63: পাঠিয়ে হামলার হুমকিও দেওয� আমাকে
327.63 - 330.41: পাকিস্তানি একটা এজেন্সি থেকে অনেকবার
330.41 - 331.99: আমাকে থ্রেড করেছে আমার ছেলেকে
331.99 - 333.79: কিডন্যাপ করার থ্রেড করেছিল আমি
333.79 - 335.19: কোনদিন সংবাদ মাধ্যমে এই বিষয়ে
335.19 - 337.93: বলিনি আমি পুলিশকে জানিয়েছিলাম পুলিশ
337.93 - 340.46: ব্যবস্থা করছিল আমার মনে হচ্ছে
340.46 - 341.98: তারই পরিণাম এটা ফোন করে
341.98 - 343.50: হুমকি দেওয়া হচ্ছিল এবং তার
343.50 - 345.72: কাছে আন্তর্জাতিক থ্রেড কল আসছিল
345.72 - 347.38: পাকিস্তানি এজেন্সি থেকে ফোন করা
347.38 - 349.16: হচ্ছিল এবং তাকে তার ওপর
349.16 - 350.74: হামলা চালালো তার পার্টি অফিসে
350.74 - 353.12: হামলা চালালো এমনকি তার ছেলেকে
353.12 - 355.56: অপহরণের হুমকি পর্যন্ত দেওয়া হয়েছিল
355.56 - 357.28: এই ঘটনার পর তিনি হাওড়া
357.28 - 359.44: সিটি পুলিশের উচ্চপদস্থ আধিকারিকদের বিষয়টি
359.44 - 362.03: জা তারপর সেই তদন্ত কিন্তু
362.03 - 364.97: করেছিল এবং এই তদন্তের প্রেক্ষিতেই
364.97 - 366.59: যে হামিদকে গ্রেপ্তার করা হয়েছে
366.59 - 368.19: এমনটাই তিনি অনুমান করছেন এবং
368.19 - 369.79: তাকে যে ফোন করে হুমকি

,Video,WER %,CER %,Word Accuracy %,GT Words,Pred Words,Correct Words,Substitutions,Deletions (Missed),Insertions
0,Rain,16.74,10.06,83.72,215,203,180,22,13,1
1,Delhi Protest,16.67,4.91,86.02,186,184,160,19,7,5
2,Subhendu CM,17.25,11.71,84.98,626,580,532,34,60,14
3,Dengue,14.84,6.58,86.26,364,362,314,44,6,4
4,Terrorist(Long),19.63,9.58,83.18,2527,2477,2102,304,121,71
5,Taslima Nasrin(Long),18.99,11.97,83.48,2670,2517,2229,222,219,66
6,Shamik(Long),20.19,8.96,83.39,2625,2659,2189,376,60,94
7,10am News(Long),20.64,9.90,82.04,2456,2405,2015,324,117,66